CREATE TABLE `guild` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` tinytext,
  `chairman` bigint(20) DEFAULT NULL,
  `vice_chairmen` text,
  `icon` text,
  `title` text,
  `level` int(11) DEFAULT NULL,
  `members` text,
  `ctime` bigint(20) DEFAULT NULL,
  `join_model` tinyint(4) DEFAULT NULL,
  `exp` int(11) DEFAULT NULL,
  `chats` text,
  `help_list` text,
  `dissolve_time` bigint(20) DEFAULT NULL,
  `applied_list` text,
  `mtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `task_last_refresh_time` bigint(20) DEFAULT NULL,
  `tasks` text,
  `member_last_login_time` bigint(20) DEFAULT NULL,
  `chairman_last_login_time` bigint(20) DEFAULT NULL,
  `clear_flag` tinyint(4) DEFAULT NULL,
  `area` tinyint(4) DEFAULT NULL,
  `guild_greetings` text,
  `help_requests` longtext,
  `last_send_group_mail_time` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10020 DEFAULT CHARSET=utf8mb4;