// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.5
// source: shared/protobuf/proto/announcement.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VOBanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int32  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                   //页签类型
	Jump          string `protobuf:"bytes,3,opt,name=jump,proto3" json:"jump,omitempty"`                    //跳转
	Image         string `protobuf:"bytes,4,opt,name=Image,proto3" json:"Image,omitempty"`                  //图片地址
	StartTime     int64  `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`         //开始时间
	EndTime       int64  `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty"`             //结束时间
	ShowStartTime int64  `protobuf:"varint,7,opt,name=showStartTime,proto3" json:"showStartTime,omitempty"` //显示的开始时间
	ShowEndTime   int64  `protobuf:"varint,8,opt,name=showEndTime,proto3" json:"showEndTime,omitempty"`     //显示的结束时间
	Priority      int32  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`           //排序优先级
}

func (x *VOBanner) Reset() {
	*x = VOBanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_announcement_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VOBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VOBanner) ProtoMessage() {}

func (x *VOBanner) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_announcement_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VOBanner.ProtoReflect.Descriptor instead.
func (*VOBanner) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_announcement_proto_rawDescGZIP(), []int{0}
}

func (x *VOBanner) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VOBanner) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *VOBanner) GetJump() string {
	if x != nil {
		return x.Jump
	}
	return ""
}

func (x *VOBanner) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *VOBanner) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *VOBanner) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *VOBanner) GetShowStartTime() int64 {
	if x != nil {
		return x.ShowStartTime
	}
	return 0
}

func (x *VOBanner) GetShowEndTime() int64 {
	if x != nil {
		return x.ShowEndTime
	}
	return 0
}

func (x *VOBanner) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type VOAnnouncement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int32  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                   //页签类型
	Title         string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                  //标题
	Content       string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`              //内容
	Tag           int32  `protobuf:"varint,5,opt,name=tag,proto3" json:"tag,omitempty"`                     //标签
	Image         string `protobuf:"bytes,6,opt,name=Image,proto3" json:"Image,omitempty"`                  //图片地址
	StartTime     int64  `protobuf:"varint,7,opt,name=startTime,proto3" json:"startTime,omitempty"`         //开始时间
	EndTime       int64  `protobuf:"varint,8,opt,name=endTime,proto3" json:"endTime,omitempty"`             //结束时间
	ShowStartTime int64  `protobuf:"varint,9,opt,name=showStartTime,proto3" json:"showStartTime,omitempty"` //显示的开始时间
	ShowEndTime   int64  `protobuf:"varint,10,opt,name=showEndTime,proto3" json:"showEndTime,omitempty"`    //显示的结束时间
	Priority      int32  `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`          //排序优先级
}

func (x *VOAnnouncement) Reset() {
	*x = VOAnnouncement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_announcement_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VOAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VOAnnouncement) ProtoMessage() {}

func (x *VOAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_announcement_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VOAnnouncement.ProtoReflect.Descriptor instead.
func (*VOAnnouncement) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_announcement_proto_rawDescGZIP(), []int{1}
}

func (x *VOAnnouncement) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VOAnnouncement) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *VOAnnouncement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VOAnnouncement) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VOAnnouncement) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *VOAnnouncement) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *VOAnnouncement) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *VOAnnouncement) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *VOAnnouncement) GetShowStartTime() int64 {
	if x != nil {
		return x.ShowStartTime
	}
	return 0
}

func (x *VOAnnouncement) GetShowEndTime() int64 {
	if x != nil {
		return x.ShowEndTime
	}
	return 0
}

func (x *VOAnnouncement) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type VOForeplayCaution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content   string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Image     string `protobuf:"bytes,3,opt,name=Image,proto3" json:"Image,omitempty"`
	StartTime int64  `protobuf:"varint,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   int64  `protobuf:"varint,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *VOForeplayCaution) Reset() {
	*x = VOForeplayCaution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_announcement_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VOForeplayCaution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VOForeplayCaution) ProtoMessage() {}

func (x *VOForeplayCaution) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_announcement_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VOForeplayCaution.ProtoReflect.Descriptor instead.
func (*VOForeplayCaution) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_announcement_proto_rawDescGZIP(), []int{2}
}

func (x *VOForeplayCaution) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VOForeplayCaution) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VOForeplayCaution) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *VOForeplayCaution) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *VOForeplayCaution) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_shared_protobuf_proto_announcement_proto protoreflect.FileDescriptor

var file_shared_protobuf_proto_announcement_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf4, 0x01, 0x0a, 0x08, 0x56,
	0x4f, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6a,
	0x75, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x73, 0x68, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x73, 0x68, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x45, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x45, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x22, 0xa8, 0x02, 0x0a, 0x0e, 0x56, 0x4f, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x68, 0x6f, 0x77,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0d, 0x73, 0x68, 0x6f, 0x77, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0x8b, 0x01, 0x0a,
	0x11, 0x56, 0x4f, 0x46, 0x6f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x43, 0x61, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_protobuf_proto_announcement_proto_rawDescOnce sync.Once
	file_shared_protobuf_proto_announcement_proto_rawDescData = file_shared_protobuf_proto_announcement_proto_rawDesc
)

func file_shared_protobuf_proto_announcement_proto_rawDescGZIP() []byte {
	file_shared_protobuf_proto_announcement_proto_rawDescOnce.Do(func() {
		file_shared_protobuf_proto_announcement_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_protobuf_proto_announcement_proto_rawDescData)
	})
	return file_shared_protobuf_proto_announcement_proto_rawDescData
}

var file_shared_protobuf_proto_announcement_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shared_protobuf_proto_announcement_proto_goTypes = []interface{}{
	(*VOBanner)(nil),          // 0: VOBanner
	(*VOAnnouncement)(nil),    // 1: VOAnnouncement
	(*VOForeplayCaution)(nil), // 2: VOForeplayCaution
}
var file_shared_protobuf_proto_announcement_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_protobuf_proto_announcement_proto_init() }
func file_shared_protobuf_proto_announcement_proto_init() {
	if File_shared_protobuf_proto_announcement_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_protobuf_proto_announcement_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VOBanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_announcement_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VOAnnouncement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_announcement_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VOForeplayCaution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_protobuf_proto_announcement_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_protobuf_proto_announcement_proto_goTypes,
		DependencyIndexes: file_shared_protobuf_proto_announcement_proto_depIdxs,
		MessageInfos:      file_shared_protobuf_proto_announcement_proto_msgTypes,
	}.Build()
	File_shared_protobuf_proto_announcement_proto = out.File
	file_shared_protobuf_proto_announcement_proto_rawDesc = nil
	file_shared_protobuf_proto_announcement_proto_goTypes = nil
	file_shared_protobuf_proto_announcement_proto_depIdxs = nil
}
