// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.5
// source: shared/protobuf/proto/character.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------ 角色列表 ------------
type C2SGetCharacterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SGetCharacterList) Reset() {
	*x = C2SGetCharacterList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGetCharacterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGetCharacterList) ProtoMessage() {}

func (x *C2SGetCharacterList) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGetCharacterList.ProtoReflect.Descriptor instead.
func (*C2SGetCharacterList) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{0}
}

type S2CGetCharacterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Characters []*VOUserCharacter `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"` // 角色列表
}

func (x *S2CGetCharacterList) Reset() {
	*x = S2CGetCharacterList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGetCharacterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGetCharacterList) ProtoMessage() {}

func (x *S2CGetCharacterList) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGetCharacterList.ProtoReflect.Descriptor instead.
func (*S2CGetCharacterList) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{1}
}

func (x *S2CGetCharacterList) GetCharacters() []*VOUserCharacter {
	if x != nil {
		return x.Characters
	}
	return nil
}

// ------------ 角色升级 ------------
type C2SCharacterLvUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32         `protobuf:"varint,1,opt,name=characterId,proto3" json:"characterId,omitempty"` // 角色ID
	Costs       []*VOResource `protobuf:"bytes,2,rep,name=costs,proto3" json:"costs,omitempty"`              // 消耗
}

func (x *C2SCharacterLvUp) Reset() {
	*x = C2SCharacterLvUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SCharacterLvUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCharacterLvUp) ProtoMessage() {}

func (x *C2SCharacterLvUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCharacterLvUp.ProtoReflect.Descriptor instead.
func (*C2SCharacterLvUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{2}
}

func (x *C2SCharacterLvUp) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *C2SCharacterLvUp) GetCosts() []*VOResource {
	if x != nil {
		return x.Costs
	}
	return nil
}

type S2CCharacterLvUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result         *VOUserCharacter  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`                 // 角色数据
	ResourceResult *VOResourceResult `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"` // 玩家资源
}

func (x *S2CCharacterLvUp) Reset() {
	*x = S2CCharacterLvUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CCharacterLvUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCharacterLvUp) ProtoMessage() {}

func (x *S2CCharacterLvUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCharacterLvUp.ProtoReflect.Descriptor instead.
func (*S2CCharacterLvUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{3}
}

func (x *S2CCharacterLvUp) GetResult() *VOUserCharacter {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CCharacterLvUp) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

// ------------ 角色升星 ------------
type C2SCharacterStarUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=characterId,proto3" json:"characterId,omitempty"` // 角色ID
}

func (x *C2SCharacterStarUp) Reset() {
	*x = C2SCharacterStarUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SCharacterStarUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCharacterStarUp) ProtoMessage() {}

func (x *C2SCharacterStarUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCharacterStarUp.ProtoReflect.Descriptor instead.
func (*C2SCharacterStarUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{4}
}

func (x *C2SCharacterStarUp) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type S2CCharacterStarUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result         *VOUserCharacter  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`                 // 角色数据
	ResourceResult *VOResourceResult `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"` // 玩家资源
}

func (x *S2CCharacterStarUp) Reset() {
	*x = S2CCharacterStarUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CCharacterStarUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCharacterStarUp) ProtoMessage() {}

func (x *S2CCharacterStarUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCharacterStarUp.ProtoReflect.Descriptor instead.
func (*S2CCharacterStarUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{5}
}

func (x *S2CCharacterStarUp) GetResult() *VOUserCharacter {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CCharacterStarUp) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

// ------------ 角色升阶 ------------
type C2SCharacterStageUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=characterId,proto3" json:"characterId,omitempty"` // 角色ID
}

func (x *C2SCharacterStageUp) Reset() {
	*x = C2SCharacterStageUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SCharacterStageUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCharacterStageUp) ProtoMessage() {}

func (x *C2SCharacterStageUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCharacterStageUp.ProtoReflect.Descriptor instead.
func (*C2SCharacterStageUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{6}
}

func (x *C2SCharacterStageUp) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type S2CCharacterStageUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result         *VOUserCharacter  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`                 // 角色ID
	ResourceResult *VOResourceResult `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"` // 玩家资源
}

func (x *S2CCharacterStageUp) Reset() {
	*x = S2CCharacterStageUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CCharacterStageUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCharacterStageUp) ProtoMessage() {}

func (x *S2CCharacterStageUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCharacterStageUp.ProtoReflect.Descriptor instead.
func (*S2CCharacterStageUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{7}
}

func (x *S2CCharacterStageUp) GetResult() *VOUserCharacter {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *S2CCharacterStageUp) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

// ------------ 角色技能升级 ------------
type C2SCharacterSkillLvUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=characterId,proto3" json:"characterId,omitempty"` // 角色ID
	SkillId     int32 `protobuf:"varint,2,opt,name=skillId,proto3" json:"skillId,omitempty"`         // 技能ID
	LvUpAmount  int32 `protobuf:"varint,3,opt,name=lvUpAmount,proto3" json:"lvUpAmount,omitempty"`   // 技能升级量
}

func (x *C2SCharacterSkillLvUp) Reset() {
	*x = C2SCharacterSkillLvUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SCharacterSkillLvUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCharacterSkillLvUp) ProtoMessage() {}

func (x *C2SCharacterSkillLvUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCharacterSkillLvUp.ProtoReflect.Descriptor instead.
func (*C2SCharacterSkillLvUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{8}
}

func (x *C2SCharacterSkillLvUp) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *C2SCharacterSkillLvUp) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *C2SCharacterSkillLvUp) GetLvUpAmount() int32 {
	if x != nil {
		return x.LvUpAmount
	}
	return 0
}

type S2CCharacterSkillLvUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Character      *VOUserCharacter  `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`           // 角色数据
	ResourceResult *VOResourceResult `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"` // 玩家资源
}

func (x *S2CCharacterSkillLvUp) Reset() {
	*x = S2CCharacterSkillLvUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CCharacterSkillLvUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCharacterSkillLvUp) ProtoMessage() {}

func (x *S2CCharacterSkillLvUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCharacterSkillLvUp.ProtoReflect.Descriptor instead.
func (*S2CCharacterSkillLvUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{9}
}

func (x *S2CCharacterSkillLvUp) GetCharacter() *VOUserCharacter {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *S2CCharacterSkillLvUp) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

// ------------ 穿戴装备 ------------
type C2SCharacterWear struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterID   int32   `protobuf:"varint,1,opt,name=characterID,proto3" json:"characterID,omitempty"`            // 角色ID
	EquipmentUIDs []int64 `protobuf:"varint,2,rep,packed,name=equipmentUIDs,proto3" json:"equipmentUIDs,omitempty"` // 装备唯一ID数组
	WorldItemUIDs []int64 `protobuf:"varint,3,rep,packed,name=worldItemUIDs,proto3" json:"worldItemUIDs,omitempty"` // 世界级道具唯一ID数据
}

func (x *C2SCharacterWear) Reset() {
	*x = C2SCharacterWear{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SCharacterWear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCharacterWear) ProtoMessage() {}

func (x *C2SCharacterWear) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCharacterWear.ProtoReflect.Descriptor instead.
func (*C2SCharacterWear) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{10}
}

func (x *C2SCharacterWear) GetCharacterID() int32 {
	if x != nil {
		return x.CharacterID
	}
	return 0
}

func (x *C2SCharacterWear) GetEquipmentUIDs() []int64 {
	if x != nil {
		return x.EquipmentUIDs
	}
	return nil
}

func (x *C2SCharacterWear) GetWorldItemUIDs() []int64 {
	if x != nil {
		return x.WorldItemUIDs
	}
	return nil
}

type S2CCharacterWear struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equipments []*VOUserEquipment `protobuf:"bytes,1,rep,name=equipments,proto3" json:"equipments,omitempty"` // 影响的装备数组
	WorldItems []*VOUserWorldItem `protobuf:"bytes,2,rep,name=worldItems,proto3" json:"worldItems,omitempty"` // 影响的世界级道具数组
}

func (x *S2CCharacterWear) Reset() {
	*x = S2CCharacterWear{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CCharacterWear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCharacterWear) ProtoMessage() {}

func (x *S2CCharacterWear) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCharacterWear.ProtoReflect.Descriptor instead.
func (*S2CCharacterWear) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{11}
}

func (x *S2CCharacterWear) GetEquipments() []*VOUserEquipment {
	if x != nil {
		return x.Equipments
	}
	return nil
}

func (x *S2CCharacterWear) GetWorldItems() []*VOUserWorldItem {
	if x != nil {
		return x.WorldItems
	}
	return nil
}

// ------------ 卸下装备 ------------
type C2SCharacterUndress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterID   int32   `protobuf:"varint,1,opt,name=characterID,proto3" json:"characterID,omitempty"`            // 角色ID
	EquipmentUIDs []int64 `protobuf:"varint,2,rep,packed,name=equipmentUIDs,proto3" json:"equipmentUIDs,omitempty"` // 装备唯一ID数组
	WorldItemUIDs []int64 `protobuf:"varint,3,rep,packed,name=worldItemUIDs,proto3" json:"worldItemUIDs,omitempty"` // 世界级道具唯一ID数据
}

func (x *C2SCharacterUndress) Reset() {
	*x = C2SCharacterUndress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SCharacterUndress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SCharacterUndress) ProtoMessage() {}

func (x *C2SCharacterUndress) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SCharacterUndress.ProtoReflect.Descriptor instead.
func (*C2SCharacterUndress) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{12}
}

func (x *C2SCharacterUndress) GetCharacterID() int32 {
	if x != nil {
		return x.CharacterID
	}
	return 0
}

func (x *C2SCharacterUndress) GetEquipmentUIDs() []int64 {
	if x != nil {
		return x.EquipmentUIDs
	}
	return nil
}

func (x *C2SCharacterUndress) GetWorldItemUIDs() []int64 {
	if x != nil {
		return x.WorldItemUIDs
	}
	return nil
}

type S2CCharacterUndress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equipments []*VOUserEquipment `protobuf:"bytes,1,rep,name=equipments,proto3" json:"equipments,omitempty"` // 影响的装备数组
	WorldItems []*VOUserWorldItem `protobuf:"bytes,2,rep,name=worldItems,proto3" json:"worldItems,omitempty"` // 影响的世界级道具数组
}

func (x *S2CCharacterUndress) Reset() {
	*x = S2CCharacterUndress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_character_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CCharacterUndress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CCharacterUndress) ProtoMessage() {}

func (x *S2CCharacterUndress) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_character_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CCharacterUndress.ProtoReflect.Descriptor instead.
func (*S2CCharacterUndress) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_character_proto_rawDescGZIP(), []int{13}
}

func (x *S2CCharacterUndress) GetEquipments() []*VOUserEquipment {
	if x != nil {
		return x.Equipments
	}
	return nil
}

func (x *S2CCharacterUndress) GetWorldItems() []*VOUserWorldItem {
	if x != nil {
		return x.WorldItems
	}
	return nil
}

var File_shared_protobuf_proto_character_proto protoreflect.FileDescriptor

var file_shared_protobuf_proto_character_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x32, 0x53, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x47,
	0x0a, 0x13, 0x53, 0x32, 0x43, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56, 0x4f, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x22, 0x57, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4c, 0x76, 0x55, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x05, 0x63, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x56,
	0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x05, 0x63, 0x6f, 0x73, 0x74, 0x73,
	0x22, 0x77, 0x0a, 0x10, 0x53, 0x32, 0x43, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x4c, 0x76, 0x55, 0x70, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56, 0x4f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39,
	0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x36, 0x0a, 0x12, 0x43, 0x32, 0x53,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x55, 0x70, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x79, 0x0a, 0x12, 0x53, 0x32, 0x43, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x72, 0x55, 0x70, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56, 0x4f, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x37, 0x0a, 0x13,
	0x43, 0x32, 0x53, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x55, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x7a, 0x0a, 0x13, 0x53, 0x32, 0x43, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x67, 0x65, 0x55, 0x70, 0x12, 0x28, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56,
	0x4f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x73, 0x0a, 0x15, 0x43, 0x32, 0x53, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x76, 0x55, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x76, 0x55, 0x70, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x76, 0x55, 0x70,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x15, 0x53, 0x32, 0x43, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x76, 0x55, 0x70,
	0x12, 0x2e, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56, 0x4f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x10,
	0x43, 0x32, 0x53, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x57, 0x65, 0x61, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x55,
	0x49, 0x44, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0d, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x55, 0x49, 0x44, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x49, 0x44, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x0d, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x49, 0x44, 0x73, 0x22, 0x76,
	0x0a, 0x10, 0x53, 0x32, 0x43, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x57, 0x65,
	0x61, 0x72, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56, 0x4f, 0x55, 0x73, 0x65, 0x72, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56, 0x4f, 0x55, 0x73, 0x65,
	0x72, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x13, 0x43, 0x32, 0x53, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x6e, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x24, 0x0a, 0x0d, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x49, 0x44,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0d, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x55, 0x49, 0x44, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x55, 0x49, 0x44, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0d, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x49, 0x44, 0x73, 0x22, 0x79, 0x0a, 0x13,
	0x53, 0x32, 0x43, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x6e, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56, 0x4f, 0x55, 0x73, 0x65, 0x72,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56, 0x4f, 0x55, 0x73,
	0x65, 0x72, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_protobuf_proto_character_proto_rawDescOnce sync.Once
	file_shared_protobuf_proto_character_proto_rawDescData = file_shared_protobuf_proto_character_proto_rawDesc
)

func file_shared_protobuf_proto_character_proto_rawDescGZIP() []byte {
	file_shared_protobuf_proto_character_proto_rawDescOnce.Do(func() {
		file_shared_protobuf_proto_character_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_protobuf_proto_character_proto_rawDescData)
	})
	return file_shared_protobuf_proto_character_proto_rawDescData
}

var file_shared_protobuf_proto_character_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_shared_protobuf_proto_character_proto_goTypes = []interface{}{
	(*C2SGetCharacterList)(nil),   // 0: C2SGetCharacterList
	(*S2CGetCharacterList)(nil),   // 1: S2CGetCharacterList
	(*C2SCharacterLvUp)(nil),      // 2: C2SCharacterLvUp
	(*S2CCharacterLvUp)(nil),      // 3: S2CCharacterLvUp
	(*C2SCharacterStarUp)(nil),    // 4: C2SCharacterStarUp
	(*S2CCharacterStarUp)(nil),    // 5: S2CCharacterStarUp
	(*C2SCharacterStageUp)(nil),   // 6: C2SCharacterStageUp
	(*S2CCharacterStageUp)(nil),   // 7: S2CCharacterStageUp
	(*C2SCharacterSkillLvUp)(nil), // 8: C2SCharacterSkillLvUp
	(*S2CCharacterSkillLvUp)(nil), // 9: S2CCharacterSkillLvUp
	(*C2SCharacterWear)(nil),      // 10: C2SCharacterWear
	(*S2CCharacterWear)(nil),      // 11: S2CCharacterWear
	(*C2SCharacterUndress)(nil),   // 12: C2SCharacterUndress
	(*S2CCharacterUndress)(nil),   // 13: S2CCharacterUndress
	(*VOUserCharacter)(nil),       // 14: VOUserCharacter
	(*VOResource)(nil),            // 15: VOResource
	(*VOResourceResult)(nil),      // 16: VOResourceResult
	(*VOUserEquipment)(nil),       // 17: VOUserEquipment
	(*VOUserWorldItem)(nil),       // 18: VOUserWorldItem
}
var file_shared_protobuf_proto_character_proto_depIdxs = []int32{
	14, // 0: S2CGetCharacterList.characters:type_name -> VOUserCharacter
	15, // 1: C2SCharacterLvUp.costs:type_name -> VOResource
	14, // 2: S2CCharacterLvUp.result:type_name -> VOUserCharacter
	16, // 3: S2CCharacterLvUp.resourceResult:type_name -> VOResourceResult
	14, // 4: S2CCharacterStarUp.result:type_name -> VOUserCharacter
	16, // 5: S2CCharacterStarUp.resourceResult:type_name -> VOResourceResult
	14, // 6: S2CCharacterStageUp.result:type_name -> VOUserCharacter
	16, // 7: S2CCharacterStageUp.resourceResult:type_name -> VOResourceResult
	14, // 8: S2CCharacterSkillLvUp.character:type_name -> VOUserCharacter
	16, // 9: S2CCharacterSkillLvUp.resourceResult:type_name -> VOResourceResult
	17, // 10: S2CCharacterWear.equipments:type_name -> VOUserEquipment
	18, // 11: S2CCharacterWear.worldItems:type_name -> VOUserWorldItem
	17, // 12: S2CCharacterUndress.equipments:type_name -> VOUserEquipment
	18, // 13: S2CCharacterUndress.worldItems:type_name -> VOUserWorldItem
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_shared_protobuf_proto_character_proto_init() }
func file_shared_protobuf_proto_character_proto_init() {
	if File_shared_protobuf_proto_character_proto != nil {
		return
	}
	file_shared_protobuf_proto_vo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_shared_protobuf_proto_character_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGetCharacterList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGetCharacterList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SCharacterLvUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CCharacterLvUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SCharacterStarUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CCharacterStarUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SCharacterStageUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CCharacterStageUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SCharacterSkillLvUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CCharacterSkillLvUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SCharacterWear); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CCharacterWear); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SCharacterUndress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_character_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CCharacterUndress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_protobuf_proto_character_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_protobuf_proto_character_proto_goTypes,
		DependencyIndexes: file_shared_protobuf_proto_character_proto_depIdxs,
		MessageInfos:      file_shared_protobuf_proto_character_proto_msgTypes,
	}.Build()
	File_shared_protobuf_proto_character_proto = out.File
	file_shared_protobuf_proto_character_proto_rawDesc = nil
	file_shared_protobuf_proto_character_proto_goTypes = nil
	file_shared_protobuf_proto_character_proto_depIdxs = nil
}
