// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.5
// source: shared/protobuf/proto/gm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReloadWhiteListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadWhiteListReq) Reset() {
	*x = ReloadWhiteListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_gm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadWhiteListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadWhiteListReq) ProtoMessage() {}

func (x *ReloadWhiteListReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_gm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadWhiteListReq.ProtoReflect.Descriptor instead.
func (*ReloadWhiteListReq) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_gm_proto_rawDescGZIP(), []int{0}
}

type ReloadWhiteListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadWhiteListResp) Reset() {
	*x = ReloadWhiteListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_gm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadWhiteListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadWhiteListResp) ProtoMessage() {}

func (x *ReloadWhiteListResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_gm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadWhiteListResp.ProtoReflect.Descriptor instead.
func (*ReloadWhiteListResp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_gm_proto_rawDescGZIP(), []int{1}
}

type ReloadMaintainReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadMaintainReq) Reset() {
	*x = ReloadMaintainReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_gm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadMaintainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadMaintainReq) ProtoMessage() {}

func (x *ReloadMaintainReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_gm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadMaintainReq.ProtoReflect.Descriptor instead.
func (*ReloadMaintainReq) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_gm_proto_rawDescGZIP(), []int{2}
}

type ReloadMaintainResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadMaintainResp) Reset() {
	*x = ReloadMaintainResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_gm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadMaintainResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadMaintainResp) ProtoMessage() {}

func (x *ReloadMaintainResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_gm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadMaintainResp.ProtoReflect.Descriptor instead.
func (*ReloadMaintainResp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_gm_proto_rawDescGZIP(), []int{3}
}

type ReloadAnnouncementReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadAnnouncementReq) Reset() {
	*x = ReloadAnnouncementReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_gm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadAnnouncementReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadAnnouncementReq) ProtoMessage() {}

func (x *ReloadAnnouncementReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_gm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadAnnouncementReq.ProtoReflect.Descriptor instead.
func (*ReloadAnnouncementReq) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_gm_proto_rawDescGZIP(), []int{4}
}

type ReloadAnnouncementResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadAnnouncementResp) Reset() {
	*x = ReloadAnnouncementResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_gm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadAnnouncementResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadAnnouncementResp) ProtoMessage() {}

func (x *ReloadAnnouncementResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_gm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadAnnouncementResp.ProtoReflect.Descriptor instead.
func (*ReloadAnnouncementResp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_gm_proto_rawDescGZIP(), []int{5}
}

var File_shared_protobuf_proto_gm_proto protoreflect.FileDescriptor

var file_shared_protobuf_proto_gm_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64,
	0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x13, 0x0a,
	0x11, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x6c, 0x6f,
	0x61, 0x64, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x22, 0x18, 0x0a, 0x16, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x6e, 0x6f, 0x75,
	0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_protobuf_proto_gm_proto_rawDescOnce sync.Once
	file_shared_protobuf_proto_gm_proto_rawDescData = file_shared_protobuf_proto_gm_proto_rawDesc
)

func file_shared_protobuf_proto_gm_proto_rawDescGZIP() []byte {
	file_shared_protobuf_proto_gm_proto_rawDescOnce.Do(func() {
		file_shared_protobuf_proto_gm_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_protobuf_proto_gm_proto_rawDescData)
	})
	return file_shared_protobuf_proto_gm_proto_rawDescData
}

var file_shared_protobuf_proto_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_protobuf_proto_gm_proto_goTypes = []interface{}{
	(*ReloadWhiteListReq)(nil),     // 0: ReloadWhiteListReq
	(*ReloadWhiteListResp)(nil),    // 1: ReloadWhiteListResp
	(*ReloadMaintainReq)(nil),      // 2: ReloadMaintainReq
	(*ReloadMaintainResp)(nil),     // 3: ReloadMaintainResp
	(*ReloadAnnouncementReq)(nil),  // 4: ReloadAnnouncementReq
	(*ReloadAnnouncementResp)(nil), // 5: ReloadAnnouncementResp
}
var file_shared_protobuf_proto_gm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_protobuf_proto_gm_proto_init() }
func file_shared_protobuf_proto_gm_proto_init() {
	if File_shared_protobuf_proto_gm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_protobuf_proto_gm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadWhiteListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_gm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadWhiteListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_gm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadMaintainReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_gm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadMaintainResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_gm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadAnnouncementReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_gm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadAnnouncementResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_protobuf_proto_gm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_protobuf_proto_gm_proto_goTypes,
		DependencyIndexes: file_shared_protobuf_proto_gm_proto_depIdxs,
		MessageInfos:      file_shared_protobuf_proto_gm_proto_msgTypes,
	}.Build()
	File_shared_protobuf_proto_gm_proto = out.File
	file_shared_protobuf_proto_gm_proto_rawDesc = nil
	file_shared_protobuf_proto_gm_proto_goTypes = nil
	file_shared_protobuf_proto_gm_proto_depIdxs = nil
}
