// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.5
// source: shared/protobuf/proto/graveyard.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2SGraveyardGetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SGraveyardGetInfo) Reset() {
	*x = C2SGraveyardGetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardGetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardGetInfo) ProtoMessage() {}

func (x *C2SGraveyardGetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardGetInfo.ProtoReflect.Descriptor instead.
func (*C2SGraveyardGetInfo) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{0}
}

type S2CGraveyardGetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Builds           []*VOGraveyardBuild `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	SendRequestCount int32               `protobuf:"varint,2,opt,name=sendRequestCount,proto3" json:"sendRequestCount,omitempty"` // 今日请求帮助次数
	RewardHours      []int32             `protobuf:"varint,3,rep,packed,name=RewardHours,proto3" json:"RewardHours,omitempty"`    // 今日随机区间(小时)
}

func (x *S2CGraveyardGetInfo) Reset() {
	*x = S2CGraveyardGetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardGetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardGetInfo) ProtoMessage() {}

func (x *S2CGraveyardGetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardGetInfo.ProtoReflect.Descriptor instead.
func (*S2CGraveyardGetInfo) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{1}
}

func (x *S2CGraveyardGetInfo) GetBuilds() []*VOGraveyardBuild {
	if x != nil {
		return x.Builds
	}
	return nil
}

func (x *S2CGraveyardGetInfo) GetSendRequestCount() int32 {
	if x != nil {
		return x.SendRequestCount
	}
	return 0
}

func (x *S2CGraveyardGetInfo) GetRewardHours() []int32 {
	if x != nil {
		return x.RewardHours
	}
	return nil
}

type C2SGraveyardRefreshBuildInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildUidList []int64 `protobuf:"varint,1,rep,packed,name=buildUidList,proto3" json:"buildUidList,omitempty"`
}

func (x *C2SGraveyardRefreshBuildInfo) Reset() {
	*x = C2SGraveyardRefreshBuildInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardRefreshBuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardRefreshBuildInfo) ProtoMessage() {}

func (x *C2SGraveyardRefreshBuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardRefreshBuildInfo.ProtoReflect.Descriptor instead.
func (*C2SGraveyardRefreshBuildInfo) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{2}
}

func (x *C2SGraveyardRefreshBuildInfo) GetBuildUidList() []int64 {
	if x != nil {
		return x.BuildUidList
	}
	return nil
}

type S2CGraveyardRefreshBuildInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildInfoList []*VOGraveyardBuild `protobuf:"bytes,1,rep,name=buildInfoList,proto3" json:"buildInfoList,omitempty"`
}

func (x *S2CGraveyardRefreshBuildInfo) Reset() {
	*x = S2CGraveyardRefreshBuildInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardRefreshBuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardRefreshBuildInfo) ProtoMessage() {}

func (x *S2CGraveyardRefreshBuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardRefreshBuildInfo.ProtoReflect.Descriptor instead.
func (*S2CGraveyardRefreshBuildInfo) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{3}
}

func (x *S2CGraveyardRefreshBuildInfo) GetBuildInfoList() []*VOGraveyardBuild {
	if x != nil {
		return x.BuildInfoList
	}
	return nil
}

type C2SGraveyardBuildCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildId  int32       `protobuf:"varint,1,opt,name=buildId,proto3" json:"buildId,omitempty"`
	Position *VOPosition `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *C2SGraveyardBuildCreate) Reset() {
	*x = C2SGraveyardBuildCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardBuildCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardBuildCreate) ProtoMessage() {}

func (x *C2SGraveyardBuildCreate) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardBuildCreate.ProtoReflect.Descriptor instead.
func (*C2SGraveyardBuildCreate) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{4}
}

func (x *C2SGraveyardBuildCreate) GetBuildId() int32 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

func (x *C2SGraveyardBuildCreate) GetPosition() *VOPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type S2CGraveyardBuildCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Build          *VOGraveyardBuild `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	ResourceResult *VOResourceResult `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"`
}

func (x *S2CGraveyardBuildCreate) Reset() {
	*x = S2CGraveyardBuildCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardBuildCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardBuildCreate) ProtoMessage() {}

func (x *S2CGraveyardBuildCreate) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardBuildCreate.ProtoReflect.Descriptor instead.
func (*S2CGraveyardBuildCreate) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{5}
}

func (x *S2CGraveyardBuildCreate) GetBuild() *VOGraveyardBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *S2CGraveyardBuildCreate) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

type C2SGraveyardBuildLvUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildUid int64 `protobuf:"varint,1,opt,name=buildUid,proto3" json:"buildUid,omitempty"`
}

func (x *C2SGraveyardBuildLvUp) Reset() {
	*x = C2SGraveyardBuildLvUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardBuildLvUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardBuildLvUp) ProtoMessage() {}

func (x *C2SGraveyardBuildLvUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardBuildLvUp.ProtoReflect.Descriptor instead.
func (*C2SGraveyardBuildLvUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{6}
}

func (x *C2SGraveyardBuildLvUp) GetBuildUid() int64 {
	if x != nil {
		return x.BuildUid
	}
	return 0
}

type S2CGraveyardBuildLvUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Build          *VOGraveyardBuild `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	ResourceResult *VOResourceResult `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"`
}

func (x *S2CGraveyardBuildLvUp) Reset() {
	*x = S2CGraveyardBuildLvUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardBuildLvUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardBuildLvUp) ProtoMessage() {}

func (x *S2CGraveyardBuildLvUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardBuildLvUp.ProtoReflect.Descriptor instead.
func (*S2CGraveyardBuildLvUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{7}
}

func (x *S2CGraveyardBuildLvUp) GetBuild() *VOGraveyardBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *S2CGraveyardBuildLvUp) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

type C2SGraveyardBuildStageUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildUid int64 `protobuf:"varint,1,opt,name=buildUid,proto3" json:"buildUid,omitempty"`
}

func (x *C2SGraveyardBuildStageUp) Reset() {
	*x = C2SGraveyardBuildStageUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardBuildStageUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardBuildStageUp) ProtoMessage() {}

func (x *C2SGraveyardBuildStageUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardBuildStageUp.ProtoReflect.Descriptor instead.
func (*C2SGraveyardBuildStageUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{8}
}

func (x *C2SGraveyardBuildStageUp) GetBuildUid() int64 {
	if x != nil {
		return x.BuildUid
	}
	return 0
}

type S2CGraveyardBuildStageUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Build          *VOGraveyardBuild `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	ResourceResult *VOResourceResult `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"`
}

func (x *S2CGraveyardBuildStageUp) Reset() {
	*x = S2CGraveyardBuildStageUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardBuildStageUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardBuildStageUp) ProtoMessage() {}

func (x *S2CGraveyardBuildStageUp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardBuildStageUp.ProtoReflect.Descriptor instead.
func (*S2CGraveyardBuildStageUp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{9}
}

func (x *S2CGraveyardBuildStageUp) GetBuild() *VOGraveyardBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *S2CGraveyardBuildStageUp) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

type C2SGraveyardProduceStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildUid   int64 `protobuf:"varint,1,opt,name=buildUid,proto3" json:"buildUid,omitempty"`
	ProduceNum int32 `protobuf:"varint,2,opt,name=produceNum,proto3" json:"produceNum,omitempty"`
}

func (x *C2SGraveyardProduceStart) Reset() {
	*x = C2SGraveyardProduceStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardProduceStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardProduceStart) ProtoMessage() {}

func (x *C2SGraveyardProduceStart) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardProduceStart.ProtoReflect.Descriptor instead.
func (*C2SGraveyardProduceStart) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{10}
}

func (x *C2SGraveyardProduceStart) GetBuildUid() int64 {
	if x != nil {
		return x.BuildUid
	}
	return 0
}

func (x *C2SGraveyardProduceStart) GetProduceNum() int32 {
	if x != nil {
		return x.ProduceNum
	}
	return 0
}

type S2CGraveyardProduceStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Builds         []*VOGraveyardBuild `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	ResourceResult *VOResourceResult   `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"`
}

func (x *S2CGraveyardProduceStart) Reset() {
	*x = S2CGraveyardProduceStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardProduceStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardProduceStart) ProtoMessage() {}

func (x *S2CGraveyardProduceStart) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardProduceStart.ProtoReflect.Descriptor instead.
func (*S2CGraveyardProduceStart) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{11}
}

func (x *S2CGraveyardProduceStart) GetBuilds() []*VOGraveyardBuild {
	if x != nil {
		return x.Builds
	}
	return nil
}

func (x *S2CGraveyardProduceStart) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

type C2SGraveyardProductionGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildUidList []int64 `protobuf:"varint,1,rep,packed,name=buildUidList,proto3" json:"buildUidList,omitempty"`
}

func (x *C2SGraveyardProductionGet) Reset() {
	*x = C2SGraveyardProductionGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardProductionGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardProductionGet) ProtoMessage() {}

func (x *C2SGraveyardProductionGet) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardProductionGet.ProtoReflect.Descriptor instead.
func (*C2SGraveyardProductionGet) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{12}
}

func (x *C2SGraveyardProductionGet) GetBuildUidList() []int64 {
	if x != nil {
		return x.BuildUidList
	}
	return nil
}

type S2CGraveyardProductionGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Builds         []*VOGraveyardBuild `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	ResourceResult *VOResourceResult   `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"`
}

func (x *S2CGraveyardProductionGet) Reset() {
	*x = S2CGraveyardProductionGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardProductionGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardProductionGet) ProtoMessage() {}

func (x *S2CGraveyardProductionGet) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardProductionGet.ProtoReflect.Descriptor instead.
func (*S2CGraveyardProductionGet) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{13}
}

func (x *S2CGraveyardProductionGet) GetBuilds() []*VOGraveyardBuild {
	if x != nil {
		return x.Builds
	}
	return nil
}

func (x *S2CGraveyardProductionGet) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

type C2SGraveyardOpenCurtain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildUid int64 `protobuf:"varint,1,opt,name=buildUid,proto3" json:"buildUid,omitempty"`
}

func (x *C2SGraveyardOpenCurtain) Reset() {
	*x = C2SGraveyardOpenCurtain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardOpenCurtain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardOpenCurtain) ProtoMessage() {}

func (x *C2SGraveyardOpenCurtain) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardOpenCurtain.ProtoReflect.Descriptor instead.
func (*C2SGraveyardOpenCurtain) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{14}
}

func (x *C2SGraveyardOpenCurtain) GetBuildUid() int64 {
	if x != nil {
		return x.BuildUid
	}
	return 0
}

type S2CGraveyardOpenCurtain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Build          *VOGraveyardBuild `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	ResourceResult *VOResourceResult `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"`
}

func (x *S2CGraveyardOpenCurtain) Reset() {
	*x = S2CGraveyardOpenCurtain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardOpenCurtain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardOpenCurtain) ProtoMessage() {}

func (x *S2CGraveyardOpenCurtain) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardOpenCurtain.ProtoReflect.Descriptor instead.
func (*S2CGraveyardOpenCurtain) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{15}
}

func (x *S2CGraveyardOpenCurtain) GetBuild() *VOGraveyardBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *S2CGraveyardOpenCurtain) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

type C2SGraveyardRelocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Relocations []*VOBuildRelocation `protobuf:"bytes,1,rep,name=relocations,proto3" json:"relocations,omitempty"`
}

func (x *C2SGraveyardRelocation) Reset() {
	*x = C2SGraveyardRelocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardRelocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardRelocation) ProtoMessage() {}

func (x *C2SGraveyardRelocation) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardRelocation.ProtoReflect.Descriptor instead.
func (*C2SGraveyardRelocation) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{16}
}

func (x *C2SGraveyardRelocation) GetRelocations() []*VOBuildRelocation {
	if x != nil {
		return x.Relocations
	}
	return nil
}

type S2CGraveyardRelocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Builds []*VOGraveyardBuild `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
}

func (x *S2CGraveyardRelocation) Reset() {
	*x = S2CGraveyardRelocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardRelocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardRelocation) ProtoMessage() {}

func (x *S2CGraveyardRelocation) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardRelocation.ProtoReflect.Descriptor instead.
func (*S2CGraveyardRelocation) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{17}
}

func (x *S2CGraveyardRelocation) GetBuilds() []*VOGraveyardBuild {
	if x != nil {
		return x.Builds
	}
	return nil
}

type C2SGraveyardCharacterDispatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildUid   int64             `protobuf:"varint,1,opt,name=buildUid,proto3" json:"buildUid,omitempty"`
	Characters []*VOCharacterPos `protobuf:"bytes,2,rep,name=characters,proto3" json:"characters,omitempty"`
}

func (x *C2SGraveyardCharacterDispatch) Reset() {
	*x = C2SGraveyardCharacterDispatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardCharacterDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardCharacterDispatch) ProtoMessage() {}

func (x *C2SGraveyardCharacterDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardCharacterDispatch.ProtoReflect.Descriptor instead.
func (*C2SGraveyardCharacterDispatch) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{18}
}

func (x *C2SGraveyardCharacterDispatch) GetBuildUid() int64 {
	if x != nil {
		return x.BuildUid
	}
	return 0
}

func (x *C2SGraveyardCharacterDispatch) GetCharacters() []*VOCharacterPos {
	if x != nil {
		return x.Characters
	}
	return nil
}

type S2CGraveyardCharacterDispatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Builds []*VOGraveyardBuild `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
}

func (x *S2CGraveyardCharacterDispatch) Reset() {
	*x = S2CGraveyardCharacterDispatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardCharacterDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardCharacterDispatch) ProtoMessage() {}

func (x *S2CGraveyardCharacterDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardCharacterDispatch.ProtoReflect.Descriptor instead.
func (*S2CGraveyardCharacterDispatch) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{19}
}

func (x *S2CGraveyardCharacterDispatch) GetBuilds() []*VOGraveyardBuild {
	if x != nil {
		return x.Builds
	}
	return nil
}

type C2SGraveyardAccelerate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildUid int64         `protobuf:"varint,1,opt,name=buildUid,proto3" json:"buildUid,omitempty"`
	Consumes []*VOResource `protobuf:"bytes,2,rep,name=consumes,proto3" json:"consumes,omitempty"`
}

func (x *C2SGraveyardAccelerate) Reset() {
	*x = C2SGraveyardAccelerate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardAccelerate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardAccelerate) ProtoMessage() {}

func (x *C2SGraveyardAccelerate) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardAccelerate.ProtoReflect.Descriptor instead.
func (*C2SGraveyardAccelerate) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{20}
}

func (x *C2SGraveyardAccelerate) GetBuildUid() int64 {
	if x != nil {
		return x.BuildUid
	}
	return 0
}

func (x *C2SGraveyardAccelerate) GetConsumes() []*VOResource {
	if x != nil {
		return x.Consumes
	}
	return nil
}

type S2CGraveyardAccelerate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceResult *VOResourceResult `protobuf:"bytes,1,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"`
	VoBuild        *VOGraveyardBuild `protobuf:"bytes,2,opt,name=voBuild,proto3" json:"voBuild,omitempty"`
}

func (x *S2CGraveyardAccelerate) Reset() {
	*x = S2CGraveyardAccelerate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardAccelerate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardAccelerate) ProtoMessage() {}

func (x *S2CGraveyardAccelerate) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardAccelerate.ProtoReflect.Descriptor instead.
func (*S2CGraveyardAccelerate) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{21}
}

func (x *S2CGraveyardAccelerate) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

func (x *S2CGraveyardAccelerate) GetVoBuild() *VOGraveyardBuild {
	if x != nil {
		return x.VoBuild
	}
	return nil
}

type C2SGraveyardPopulationSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Populations []*VOGraveyardPopulationSet `protobuf:"bytes,1,rep,name=populations,proto3" json:"populations,omitempty"`
}

func (x *C2SGraveyardPopulationSet) Reset() {
	*x = C2SGraveyardPopulationSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardPopulationSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardPopulationSet) ProtoMessage() {}

func (x *C2SGraveyardPopulationSet) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardPopulationSet.ProtoReflect.Descriptor instead.
func (*C2SGraveyardPopulationSet) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{22}
}

func (x *C2SGraveyardPopulationSet) GetPopulations() []*VOGraveyardPopulationSet {
	if x != nil {
		return x.Populations
	}
	return nil
}

type S2CGraveyardPopulationSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildInfos []*VOGraveyardBuild `protobuf:"bytes,1,rep,name=buildInfos,proto3" json:"buildInfos,omitempty"`
}

func (x *S2CGraveyardPopulationSet) Reset() {
	*x = S2CGraveyardPopulationSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardPopulationSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardPopulationSet) ProtoMessage() {}

func (x *S2CGraveyardPopulationSet) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardPopulationSet.ProtoReflect.Descriptor instead.
func (*S2CGraveyardPopulationSet) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{23}
}

func (x *S2CGraveyardPopulationSet) GetBuildInfos() []*VOGraveyardBuild {
	if x != nil {
		return x.BuildInfos
	}
	return nil
}

// 请求帮助
type C2SGraveyardSendHelpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildUid int64 `protobuf:"varint,1,opt,name=buildUid,proto3" json:"buildUid,omitempty"`
}

func (x *C2SGraveyardSendHelpRequest) Reset() {
	*x = C2SGraveyardSendHelpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardSendHelpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardSendHelpRequest) ProtoMessage() {}

func (x *C2SGraveyardSendHelpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardSendHelpRequest.ProtoReflect.Descriptor instead.
func (*C2SGraveyardSendHelpRequest) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{24}
}

func (x *C2SGraveyardSendHelpRequest) GetBuildUid() int64 {
	if x != nil {
		return x.BuildUid
	}
	return 0
}

type S2CGraveyardSendHelpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendRequestCount int32             `protobuf:"varint,1,opt,name=sendRequestCount,proto3" json:"sendRequestCount,omitempty"`
	Build            *VOGraveyardBuild `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
}

func (x *S2CGraveyardSendHelpRequest) Reset() {
	*x = S2CGraveyardSendHelpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardSendHelpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardSendHelpRequest) ProtoMessage() {}

func (x *S2CGraveyardSendHelpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardSendHelpRequest.ProtoReflect.Descriptor instead.
func (*S2CGraveyardSendHelpRequest) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{25}
}

func (x *S2CGraveyardSendHelpRequest) GetSendRequestCount() int32 {
	if x != nil {
		return x.SendRequestCount
	}
	return 0
}

func (x *S2CGraveyardSendHelpRequest) GetBuild() *VOGraveyardBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

// 收到此推送后，互助请求被处理建筑减cd
type S2CGraveyardReceiveHelp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Build *VOGraveyardBuild `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
}

func (x *S2CGraveyardReceiveHelp) Reset() {
	*x = S2CGraveyardReceiveHelp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardReceiveHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardReceiveHelp) ProtoMessage() {}

func (x *S2CGraveyardReceiveHelp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardReceiveHelp.ProtoReflect.Descriptor instead.
func (*S2CGraveyardReceiveHelp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{26}
}

func (x *S2CGraveyardReceiveHelp) GetBuild() *VOGraveyardBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

// 小人对话领奖
type C2SGraveyardReceivePlotReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SGraveyardReceivePlotReward) Reset() {
	*x = C2SGraveyardReceivePlotReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardReceivePlotReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardReceivePlotReward) ProtoMessage() {}

func (x *C2SGraveyardReceivePlotReward) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardReceivePlotReward.ProtoReflect.Descriptor instead.
func (*C2SGraveyardReceivePlotReward) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{27}
}

type S2CGraveyardReceivePlotReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceResult *VOResourceResult `protobuf:"bytes,1,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"`   // 资源变动
	RewardHours    []int32           `protobuf:"varint,2,rep,packed,name=RewardHours,proto3" json:"RewardHours,omitempty"` // 今日随机区间(小时)
}

func (x *S2CGraveyardReceivePlotReward) Reset() {
	*x = S2CGraveyardReceivePlotReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardReceivePlotReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardReceivePlotReward) ProtoMessage() {}

func (x *S2CGraveyardReceivePlotReward) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardReceivePlotReward.ProtoReflect.Descriptor instead.
func (*S2CGraveyardReceivePlotReward) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{28}
}

func (x *S2CGraveyardReceivePlotReward) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

func (x *S2CGraveyardReceivePlotReward) GetRewardHours() []int32 {
	if x != nil {
		return x.RewardHours
	}
	return nil
}

// 获得小人对话领奖区间
type C2SGraveyardGetRewardHours struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SGraveyardGetRewardHours) Reset() {
	*x = C2SGraveyardGetRewardHours{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardGetRewardHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardGetRewardHours) ProtoMessage() {}

func (x *C2SGraveyardGetRewardHours) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardGetRewardHours.ProtoReflect.Descriptor instead.
func (*C2SGraveyardGetRewardHours) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{29}
}

type S2CGraveyardGetRewardHours struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RewardHours []int32 `protobuf:"varint,1,rep,packed,name=RewardHours,proto3" json:"RewardHours,omitempty"` // 今日随机区间(小时)
}

func (x *S2CGraveyardGetRewardHours) Reset() {
	*x = S2CGraveyardGetRewardHours{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardGetRewardHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardGetRewardHours) ProtoMessage() {}

func (x *S2CGraveyardGetRewardHours) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardGetRewardHours.ProtoReflect.Descriptor instead.
func (*S2CGraveyardGetRewardHours) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{30}
}

func (x *S2CGraveyardGetRewardHours) GetRewardHours() []int32 {
	if x != nil {
		return x.RewardHours
	}
	return nil
}

// 使用模拟经营buff道具
type C2SGraveyardUseBuff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int32 `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Amount int32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *C2SGraveyardUseBuff) Reset() {
	*x = C2SGraveyardUseBuff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGraveyardUseBuff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGraveyardUseBuff) ProtoMessage() {}

func (x *C2SGraveyardUseBuff) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGraveyardUseBuff.ProtoReflect.Descriptor instead.
func (*C2SGraveyardUseBuff) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{31}
}

func (x *C2SGraveyardUseBuff) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *C2SGraveyardUseBuff) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type S2CGraveyardUseBuff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceResult *VOResourceResult   `protobuf:"bytes,1,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"` // 玩家资源
	BuildInfoList  []*VOGraveyardBuild `protobuf:"bytes,2,rep,name=buildInfoList,proto3" json:"buildInfoList,omitempty"`
}

func (x *S2CGraveyardUseBuff) Reset() {
	*x = S2CGraveyardUseBuff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGraveyardUseBuff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGraveyardUseBuff) ProtoMessage() {}

func (x *S2CGraveyardUseBuff) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_graveyard_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGraveyardUseBuff.ProtoReflect.Descriptor instead.
func (*S2CGraveyardUseBuff) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_graveyard_proto_rawDescGZIP(), []int{32}
}

func (x *S2CGraveyardUseBuff) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

func (x *S2CGraveyardUseBuff) GetBuildInfoList() []*VOGraveyardBuild {
	if x != nil {
		return x.BuildInfoList
	}
	return nil
}

var File_shared_protobuf_proto_graveyard_proto protoreflect.FileDescriptor

var file_shared_protobuf_proto_graveyard_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x32, 0x53, 0x47, 0x72,
	0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x8e,
	0x01, 0x0a, 0x13, 0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x29, 0x0a, 0x06, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65,
	0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x06, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x73, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x73, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x0b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x22,
	0x42, 0x0a, 0x1c, 0x43, 0x32, 0x53, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x22, 0x0a, 0x0c, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0c, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x57, 0x0a, 0x1c, 0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x0d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x47,
	0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x0d, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x17,
	0x43, 0x32, 0x53, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x56, 0x4f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7d, 0x0a, 0x17, 0x53, 0x32,
	0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61,
	0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x39,
	0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x33, 0x0a, 0x15, 0x43, 0x32, 0x53,
	0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x76,
	0x55, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x22, 0x7b,
	0x0a, 0x15, 0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x4c, 0x76, 0x55, 0x70, 0x12, 0x27, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65,
	0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x36, 0x0a, 0x18, 0x43,
	0x32, 0x53, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x55, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x55, 0x69, 0x64, 0x22, 0x7e, 0x0a, 0x18, 0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79,
	0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x55, 0x70, 0x12,
	0x27, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x56, 0x0a, 0x18, 0x43, 0x32, 0x53, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79,
	0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x80, 0x01, 0x0a, 0x18,
	0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x47, 0x72, 0x61,
	0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x06, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x73, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3f,
	0x0a, 0x19, 0x43, 0x32, 0x53, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x0c, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x81, 0x01, 0x0a, 0x19, 0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x12, 0x29, 0x0a,
	0x06, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x52, 0x06, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x35, 0x0a, 0x17, 0x43, 0x32, 0x53, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79,
	0x61, 0x72, 0x64, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x75, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x22, 0x7d, 0x0a, 0x17, 0x53, 0x32,
	0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x75,
	0x72, 0x74, 0x61, 0x69, 0x6e, 0x12, 0x27, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61,
	0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x39,
	0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4e, 0x0a, 0x16, 0x43, 0x32, 0x53,
	0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x52, 0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x56, 0x4f, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x72, 0x65,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x43, 0x0a, 0x16, 0x53, 0x32, 0x43,
	0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x52, 0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72,
	0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x06, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x22, 0x6c,
	0x0a, 0x1d, 0x43, 0x32, 0x53, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x0a, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x56, 0x4f, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73,
	0x52, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x22, 0x4a, 0x0a, 0x1d,
	0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x29, 0x0a,
	0x06, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x52, 0x06, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x22, 0x5d, 0x0a, 0x16, 0x43, 0x32, 0x53, 0x47,
	0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x12, 0x27,
	0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x16, 0x53, 0x32, 0x43, 0x47,
	0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a,
	0x07, 0x76, 0x6f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x07, 0x76, 0x6f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x22, 0x58, 0x0a, 0x19, 0x43, 0x32,
	0x53, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x70, 0x6f, 0x70, 0x75, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x56,
	0x4f, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x52, 0x0b, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4e, 0x0a, 0x19, 0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65,
	0x79, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x74, 0x12, 0x31, 0x0a, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79,
	0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x22, 0x39, 0x0a, 0x1b, 0x43, 0x32, 0x53, 0x47, 0x72, 0x61, 0x76, 0x65,
	0x79, 0x61, 0x72, 0x64, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x6c, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x22,
	0x72, 0x0a, 0x1b, 0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x53,
	0x65, 0x6e, 0x64, 0x48, 0x65, 0x6c, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a,
	0x0a, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x47, 0x72,
	0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x05, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x22, 0x42, 0x0a, 0x17, 0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x48, 0x65, 0x6c, 0x70, 0x12, 0x27,
	0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x52, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x32, 0x53, 0x47, 0x72,
	0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x50, 0x6c,
	0x6f, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x22, 0x7c, 0x0a, 0x1d, 0x53, 0x32, 0x43, 0x47,
	0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x50,
	0x6c, 0x6f, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x48, 0x6f,
	0x75, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x32, 0x53, 0x47, 0x72, 0x61,
	0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x48,
	0x6f, 0x75, 0x72, 0x73, 0x22, 0x3e, 0x0a, 0x1a, 0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65,
	0x79, 0x61, 0x72, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x48, 0x6f, 0x75,
	0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x48, 0x6f, 0x75, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x48,
	0x6f, 0x75, 0x72, 0x73, 0x22, 0x45, 0x0a, 0x13, 0x43, 0x32, 0x53, 0x47, 0x72, 0x61, 0x76, 0x65,
	0x79, 0x61, 0x72, 0x64, 0x55, 0x73, 0x65, 0x42, 0x75, 0x66, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x89, 0x01, 0x0a, 0x13,
	0x53, 0x32, 0x43, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79, 0x61, 0x72, 0x64, 0x55, 0x73, 0x65, 0x42,
	0x75, 0x66, 0x66, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x37,
	0x0a, 0x0d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x47, 0x72, 0x61, 0x76, 0x65, 0x79,
	0x61, 0x72, 0x64, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x0d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_protobuf_proto_graveyard_proto_rawDescOnce sync.Once
	file_shared_protobuf_proto_graveyard_proto_rawDescData = file_shared_protobuf_proto_graveyard_proto_rawDesc
)

func file_shared_protobuf_proto_graveyard_proto_rawDescGZIP() []byte {
	file_shared_protobuf_proto_graveyard_proto_rawDescOnce.Do(func() {
		file_shared_protobuf_proto_graveyard_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_protobuf_proto_graveyard_proto_rawDescData)
	})
	return file_shared_protobuf_proto_graveyard_proto_rawDescData
}

var file_shared_protobuf_proto_graveyard_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_shared_protobuf_proto_graveyard_proto_goTypes = []interface{}{
	(*C2SGraveyardGetInfo)(nil),           // 0: C2SGraveyardGetInfo
	(*S2CGraveyardGetInfo)(nil),           // 1: S2CGraveyardGetInfo
	(*C2SGraveyardRefreshBuildInfo)(nil),  // 2: C2SGraveyardRefreshBuildInfo
	(*S2CGraveyardRefreshBuildInfo)(nil),  // 3: S2CGraveyardRefreshBuildInfo
	(*C2SGraveyardBuildCreate)(nil),       // 4: C2SGraveyardBuildCreate
	(*S2CGraveyardBuildCreate)(nil),       // 5: S2CGraveyardBuildCreate
	(*C2SGraveyardBuildLvUp)(nil),         // 6: C2SGraveyardBuildLvUp
	(*S2CGraveyardBuildLvUp)(nil),         // 7: S2CGraveyardBuildLvUp
	(*C2SGraveyardBuildStageUp)(nil),      // 8: C2SGraveyardBuildStageUp
	(*S2CGraveyardBuildStageUp)(nil),      // 9: S2CGraveyardBuildStageUp
	(*C2SGraveyardProduceStart)(nil),      // 10: C2SGraveyardProduceStart
	(*S2CGraveyardProduceStart)(nil),      // 11: S2CGraveyardProduceStart
	(*C2SGraveyardProductionGet)(nil),     // 12: C2SGraveyardProductionGet
	(*S2CGraveyardProductionGet)(nil),     // 13: S2CGraveyardProductionGet
	(*C2SGraveyardOpenCurtain)(nil),       // 14: C2SGraveyardOpenCurtain
	(*S2CGraveyardOpenCurtain)(nil),       // 15: S2CGraveyardOpenCurtain
	(*C2SGraveyardRelocation)(nil),        // 16: C2SGraveyardRelocation
	(*S2CGraveyardRelocation)(nil),        // 17: S2CGraveyardRelocation
	(*C2SGraveyardCharacterDispatch)(nil), // 18: C2SGraveyardCharacterDispatch
	(*S2CGraveyardCharacterDispatch)(nil), // 19: S2CGraveyardCharacterDispatch
	(*C2SGraveyardAccelerate)(nil),        // 20: C2SGraveyardAccelerate
	(*S2CGraveyardAccelerate)(nil),        // 21: S2CGraveyardAccelerate
	(*C2SGraveyardPopulationSet)(nil),     // 22: C2SGraveyardPopulationSet
	(*S2CGraveyardPopulationSet)(nil),     // 23: S2CGraveyardPopulationSet
	(*C2SGraveyardSendHelpRequest)(nil),   // 24: C2SGraveyardSendHelpRequest
	(*S2CGraveyardSendHelpRequest)(nil),   // 25: S2CGraveyardSendHelpRequest
	(*S2CGraveyardReceiveHelp)(nil),       // 26: S2CGraveyardReceiveHelp
	(*C2SGraveyardReceivePlotReward)(nil), // 27: C2SGraveyardReceivePlotReward
	(*S2CGraveyardReceivePlotReward)(nil), // 28: S2CGraveyardReceivePlotReward
	(*C2SGraveyardGetRewardHours)(nil),    // 29: C2SGraveyardGetRewardHours
	(*S2CGraveyardGetRewardHours)(nil),    // 30: S2CGraveyardGetRewardHours
	(*C2SGraveyardUseBuff)(nil),           // 31: C2SGraveyardUseBuff
	(*S2CGraveyardUseBuff)(nil),           // 32: S2CGraveyardUseBuff
	(*VOGraveyardBuild)(nil),              // 33: VOGraveyardBuild
	(*VOPosition)(nil),                    // 34: VOPosition
	(*VOResourceResult)(nil),              // 35: VOResourceResult
	(*VOBuildRelocation)(nil),             // 36: VOBuildRelocation
	(*VOCharacterPos)(nil),                // 37: VOCharacterPos
	(*VOResource)(nil),                    // 38: VOResource
	(*VOGraveyardPopulationSet)(nil),      // 39: VOGraveyardPopulationSet
}
var file_shared_protobuf_proto_graveyard_proto_depIdxs = []int32{
	33, // 0: S2CGraveyardGetInfo.builds:type_name -> VOGraveyardBuild
	33, // 1: S2CGraveyardRefreshBuildInfo.buildInfoList:type_name -> VOGraveyardBuild
	34, // 2: C2SGraveyardBuildCreate.position:type_name -> VOPosition
	33, // 3: S2CGraveyardBuildCreate.build:type_name -> VOGraveyardBuild
	35, // 4: S2CGraveyardBuildCreate.resourceResult:type_name -> VOResourceResult
	33, // 5: S2CGraveyardBuildLvUp.build:type_name -> VOGraveyardBuild
	35, // 6: S2CGraveyardBuildLvUp.resourceResult:type_name -> VOResourceResult
	33, // 7: S2CGraveyardBuildStageUp.build:type_name -> VOGraveyardBuild
	35, // 8: S2CGraveyardBuildStageUp.resourceResult:type_name -> VOResourceResult
	33, // 9: S2CGraveyardProduceStart.builds:type_name -> VOGraveyardBuild
	35, // 10: S2CGraveyardProduceStart.resourceResult:type_name -> VOResourceResult
	33, // 11: S2CGraveyardProductionGet.builds:type_name -> VOGraveyardBuild
	35, // 12: S2CGraveyardProductionGet.resourceResult:type_name -> VOResourceResult
	33, // 13: S2CGraveyardOpenCurtain.build:type_name -> VOGraveyardBuild
	35, // 14: S2CGraveyardOpenCurtain.resourceResult:type_name -> VOResourceResult
	36, // 15: C2SGraveyardRelocation.relocations:type_name -> VOBuildRelocation
	33, // 16: S2CGraveyardRelocation.builds:type_name -> VOGraveyardBuild
	37, // 17: C2SGraveyardCharacterDispatch.characters:type_name -> VOCharacterPos
	33, // 18: S2CGraveyardCharacterDispatch.builds:type_name -> VOGraveyardBuild
	38, // 19: C2SGraveyardAccelerate.consumes:type_name -> VOResource
	35, // 20: S2CGraveyardAccelerate.resourceResult:type_name -> VOResourceResult
	33, // 21: S2CGraveyardAccelerate.voBuild:type_name -> VOGraveyardBuild
	39, // 22: C2SGraveyardPopulationSet.populations:type_name -> VOGraveyardPopulationSet
	33, // 23: S2CGraveyardPopulationSet.buildInfos:type_name -> VOGraveyardBuild
	33, // 24: S2CGraveyardSendHelpRequest.build:type_name -> VOGraveyardBuild
	33, // 25: S2CGraveyardReceiveHelp.build:type_name -> VOGraveyardBuild
	35, // 26: S2CGraveyardReceivePlotReward.resourceResult:type_name -> VOResourceResult
	35, // 27: S2CGraveyardUseBuff.resourceResult:type_name -> VOResourceResult
	33, // 28: S2CGraveyardUseBuff.buildInfoList:type_name -> VOGraveyardBuild
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_shared_protobuf_proto_graveyard_proto_init() }
func file_shared_protobuf_proto_graveyard_proto_init() {
	if File_shared_protobuf_proto_graveyard_proto != nil {
		return
	}
	file_shared_protobuf_proto_vo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_shared_protobuf_proto_graveyard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardGetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardGetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardRefreshBuildInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardRefreshBuildInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardBuildCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardBuildCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardBuildLvUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardBuildLvUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardBuildStageUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardBuildStageUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardProduceStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardProduceStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardProductionGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardProductionGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardOpenCurtain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardOpenCurtain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardRelocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardRelocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardCharacterDispatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardCharacterDispatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardAccelerate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardAccelerate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardPopulationSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardPopulationSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardSendHelpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardSendHelpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardReceiveHelp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardReceivePlotReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardReceivePlotReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardGetRewardHours); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardGetRewardHours); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGraveyardUseBuff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_graveyard_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGraveyardUseBuff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_protobuf_proto_graveyard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_protobuf_proto_graveyard_proto_goTypes,
		DependencyIndexes: file_shared_protobuf_proto_graveyard_proto_depIdxs,
		MessageInfos:      file_shared_protobuf_proto_graveyard_proto_msgTypes,
	}.Build()
	File_shared_protobuf_proto_graveyard_proto = out.File
	file_shared_protobuf_proto_graveyard_proto_rawDesc = nil
	file_shared_protobuf_proto_graveyard_proto_goTypes = nil
	file_shared_protobuf_proto_graveyard_proto_depIdxs = nil
}
