// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.5
// source: shared/protobuf/proto/login.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *CheckTokenReq) Reset() {
	*x = CheckTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenReq) ProtoMessage() {}

func (x *CheckTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenReq.ProtoReflect.Descriptor instead.
func (*CheckTokenReq) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_login_proto_rawDescGZIP(), []int{0}
}

func (x *CheckTokenReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CheckTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CheckTokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK bool `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
}

func (x *CheckTokenResp) Reset() {
	*x = CheckTokenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenResp) ProtoMessage() {}

func (x *CheckTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenResp.ProtoReflect.Descriptor instead.
func (*CheckTokenResp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_login_proto_rawDescGZIP(), []int{1}
}

func (x *CheckTokenResp) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

type LoginTestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Id  int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LoginTestReq) Reset() {
	*x = LoginTestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginTestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginTestReq) ProtoMessage() {}

func (x *LoginTestReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginTestReq.ProtoReflect.Descriptor instead.
func (*LoginTestReq) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_login_proto_rawDescGZIP(), []int{2}
}

func (x *LoginTestReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginTestReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginTestResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Id  int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LoginTestResp) Reset() {
	*x = LoginTestResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginTestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginTestResp) ProtoMessage() {}

func (x *LoginTestResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginTestResp.ProtoReflect.Descriptor instead.
func (*LoginTestResp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_login_proto_rawDescGZIP(), []int{3}
}

func (x *LoginTestResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginTestResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_shared_protobuf_proto_login_proto protoreflect.FileDescriptor

var file_shared_protobuf_proto_login_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x20, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x4f, 0x4b, 0x22, 0x30, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0x5d, 0x0a, 0x05, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x2d, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x0e, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x0f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x25, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0d, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_protobuf_proto_login_proto_rawDescOnce sync.Once
	file_shared_protobuf_proto_login_proto_rawDescData = file_shared_protobuf_proto_login_proto_rawDesc
)

func file_shared_protobuf_proto_login_proto_rawDescGZIP() []byte {
	file_shared_protobuf_proto_login_proto_rawDescOnce.Do(func() {
		file_shared_protobuf_proto_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_protobuf_proto_login_proto_rawDescData)
	})
	return file_shared_protobuf_proto_login_proto_rawDescData
}

var file_shared_protobuf_proto_login_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_protobuf_proto_login_proto_goTypes = []interface{}{
	(*CheckTokenReq)(nil),  // 0: CheckTokenReq
	(*CheckTokenResp)(nil), // 1: CheckTokenResp
	(*LoginTestReq)(nil),   // 2: LoginTestReq
	(*LoginTestResp)(nil),  // 3: LoginTestResp
}
var file_shared_protobuf_proto_login_proto_depIdxs = []int32{
	0, // 0: Login.CheckToken:input_type -> CheckTokenReq
	2, // 1: Login.Test:input_type -> LoginTestReq
	1, // 2: Login.CheckToken:output_type -> CheckTokenResp
	3, // 3: Login.Test:output_type -> LoginTestResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_protobuf_proto_login_proto_init() }
func file_shared_protobuf_proto_login_proto_init() {
	if File_shared_protobuf_proto_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_protobuf_proto_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTokenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginTestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginTestResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_protobuf_proto_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_protobuf_proto_login_proto_goTypes,
		DependencyIndexes: file_shared_protobuf_proto_login_proto_depIdxs,
		MessageInfos:      file_shared_protobuf_proto_login_proto_msgTypes,
	}.Build()
	File_shared_protobuf_proto_login_proto = out.File
	file_shared_protobuf_proto_login_proto_rawDesc = nil
	file_shared_protobuf_proto_login_proto_goTypes = nil
	file_shared_protobuf_proto_login_proto_depIdxs = nil
}
