// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.5
// source: shared/protobuf/proto/mail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailFetchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *MailFetchReq) Reset() {
	*x = MailFetchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailFetchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailFetchReq) ProtoMessage() {}

func (x *MailFetchReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailFetchReq.ProtoReflect.Descriptor instead.
func (*MailFetchReq) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{0}
}

func (x *MailFetchReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MailFetchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        int64           `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupMails    []*VOServerMail `protobuf:"bytes,2,rep,name=groupMails,proto3" json:"groupMails,omitempty"`
	PersonalMails []*VOServerMail `protobuf:"bytes,3,rep,name=personalMails,proto3" json:"personalMails,omitempty"`
}

func (x *MailFetchResp) Reset() {
	*x = MailFetchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailFetchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailFetchResp) ProtoMessage() {}

func (x *MailFetchResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailFetchResp.ProtoReflect.Descriptor instead.
func (*MailFetchResp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{1}
}

func (x *MailFetchResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MailFetchResp) GetGroupMails() []*VOServerMail {
	if x != nil {
		return x.GroupMails
	}
	return nil
}

func (x *MailFetchResp) GetPersonalMails() []*VOServerMail {
	if x != nil {
		return x.PersonalMails
	}
	return nil
}

type SendWholeServerMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId  int32         `protobuf:"varint,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Title       string        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TitleArgs   []string      `protobuf:"bytes,3,rep,name=titleArgs,proto3" json:"titleArgs,omitempty"`
	Content     string        `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ContentArgs []string      `protobuf:"bytes,5,rep,name=contentArgs,proto3" json:"contentArgs,omitempty"`
	Attachment  []*VOResource `protobuf:"bytes,6,rep,name=attachment,proto3" json:"attachment,omitempty"`
	Sender      string        `protobuf:"bytes,8,opt,name=sender,proto3" json:"sender,omitempty"`
	StartTime   int64         `protobuf:"varint,9,opt,name=startTime,proto3" json:"startTime,omitempty"`
	ExpireTime  int64         `protobuf:"varint,10,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	EndTime     int64         `protobuf:"varint,11,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *SendWholeServerMailReq) Reset() {
	*x = SendWholeServerMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendWholeServerMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWholeServerMailReq) ProtoMessage() {}

func (x *SendWholeServerMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWholeServerMailReq.ProtoReflect.Descriptor instead.
func (*SendWholeServerMailReq) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{2}
}

func (x *SendWholeServerMailReq) GetTemplateId() int32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *SendWholeServerMailReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendWholeServerMailReq) GetTitleArgs() []string {
	if x != nil {
		return x.TitleArgs
	}
	return nil
}

func (x *SendWholeServerMailReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendWholeServerMailReq) GetContentArgs() []string {
	if x != nil {
		return x.ContentArgs
	}
	return nil
}

func (x *SendWholeServerMailReq) GetAttachment() []*VOResource {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *SendWholeServerMailReq) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendWholeServerMailReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SendWholeServerMailReq) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *SendWholeServerMailReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type SendWholeServerMailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendWholeServerMailResp) Reset() {
	*x = SendWholeServerMailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendWholeServerMailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWholeServerMailResp) ProtoMessage() {}

func (x *SendWholeServerMailResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWholeServerMailResp.ProtoReflect.Descriptor instead.
func (*SendWholeServerMailResp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{3}
}

type SendGroupMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId  int32         `protobuf:"varint,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Title       string        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TitleArgs   []string      `protobuf:"bytes,3,rep,name=titleArgs,proto3" json:"titleArgs,omitempty"`
	Content     string        `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ContentArgs []string      `protobuf:"bytes,5,rep,name=contentArgs,proto3" json:"contentArgs,omitempty"`
	Attachment  []*VOResource `protobuf:"bytes,6,rep,name=attachment,proto3" json:"attachment,omitempty"`
	Sender      string        `protobuf:"bytes,8,opt,name=sender,proto3" json:"sender,omitempty"`
	StartTime   int64         `protobuf:"varint,9,opt,name=startTime,proto3" json:"startTime,omitempty"`
	ExpireTime  int64         `protobuf:"varint,10,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	EndTime     int64         `protobuf:"varint,11,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Users       []int64       `protobuf:"varint,12,rep,packed,name=users,proto3" json:"users,omitempty"`
}

func (x *SendGroupMailReq) Reset() {
	*x = SendGroupMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGroupMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMailReq) ProtoMessage() {}

func (x *SendGroupMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMailReq.ProtoReflect.Descriptor instead.
func (*SendGroupMailReq) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{4}
}

func (x *SendGroupMailReq) GetTemplateId() int32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *SendGroupMailReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendGroupMailReq) GetTitleArgs() []string {
	if x != nil {
		return x.TitleArgs
	}
	return nil
}

func (x *SendGroupMailReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendGroupMailReq) GetContentArgs() []string {
	if x != nil {
		return x.ContentArgs
	}
	return nil
}

func (x *SendGroupMailReq) GetAttachment() []*VOResource {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *SendGroupMailReq) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendGroupMailReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SendGroupMailReq) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *SendGroupMailReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SendGroupMailReq) GetUsers() []int64 {
	if x != nil {
		return x.Users
	}
	return nil
}

type SendGroupMailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendGroupMailResp) Reset() {
	*x = SendGroupMailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGroupMailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMailResp) ProtoMessage() {}

func (x *SendGroupMailResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMailResp.ProtoReflect.Descriptor instead.
func (*SendGroupMailResp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{5}
}

type SendPersonalMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId  int32         `protobuf:"varint,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Title       string        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TitleArgs   []string      `protobuf:"bytes,3,rep,name=titleArgs,proto3" json:"titleArgs,omitempty"`
	Content     string        `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ContentArgs []string      `protobuf:"bytes,5,rep,name=contentArgs,proto3" json:"contentArgs,omitempty"`
	Attachment  []*VOResource `protobuf:"bytes,6,rep,name=attachment,proto3" json:"attachment,omitempty"`
	Sender      string        `protobuf:"bytes,7,opt,name=sender,proto3" json:"sender,omitempty"`
	StartTime   int64         `protobuf:"varint,8,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime     int64         `protobuf:"varint,9,opt,name=endTime,proto3" json:"endTime,omitempty"`
	ExpireTime  int64         `protobuf:"varint,10,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	Users       []int64       `protobuf:"varint,11,rep,packed,name=users,proto3" json:"users,omitempty"`
}

func (x *SendPersonalMailReq) Reset() {
	*x = SendPersonalMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPersonalMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPersonalMailReq) ProtoMessage() {}

func (x *SendPersonalMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPersonalMailReq.ProtoReflect.Descriptor instead.
func (*SendPersonalMailReq) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{6}
}

func (x *SendPersonalMailReq) GetTemplateId() int32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *SendPersonalMailReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendPersonalMailReq) GetTitleArgs() []string {
	if x != nil {
		return x.TitleArgs
	}
	return nil
}

func (x *SendPersonalMailReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendPersonalMailReq) GetContentArgs() []string {
	if x != nil {
		return x.ContentArgs
	}
	return nil
}

func (x *SendPersonalMailReq) GetAttachment() []*VOResource {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *SendPersonalMailReq) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendPersonalMailReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SendPersonalMailReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SendPersonalMailReq) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *SendPersonalMailReq) GetUsers() []int64 {
	if x != nil {
		return x.Users
	}
	return nil
}

type SendPersonalMailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendPersonalMailResp) Reset() {
	*x = SendPersonalMailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPersonalMailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPersonalMailResp) ProtoMessage() {}

func (x *SendPersonalMailResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPersonalMailResp.ProtoReflect.Descriptor instead.
func (*SendPersonalMailResp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{7}
}

type NewGroupMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail *VOServerGroupMail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
}

func (x *NewGroupMailReq) Reset() {
	*x = NewGroupMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGroupMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGroupMailReq) ProtoMessage() {}

func (x *NewGroupMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGroupMailReq.ProtoReflect.Descriptor instead.
func (*NewGroupMailReq) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{8}
}

func (x *NewGroupMailReq) GetMail() *VOServerGroupMail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type NewGroupMailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewGroupMailResp) Reset() {
	*x = NewGroupMailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGroupMailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGroupMailResp) ProtoMessage() {}

func (x *NewGroupMailResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGroupMailResp.ProtoReflect.Descriptor instead.
func (*NewGroupMailResp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{9}
}

type NewPersonalMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail *VOServerPersonalMail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
}

func (x *NewPersonalMailReq) Reset() {
	*x = NewPersonalMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPersonalMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPersonalMailReq) ProtoMessage() {}

func (x *NewPersonalMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPersonalMailReq.ProtoReflect.Descriptor instead.
func (*NewPersonalMailReq) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{10}
}

func (x *NewPersonalMailReq) GetMail() *VOServerPersonalMail {
	if x != nil {
		return x.Mail
	}
	return nil
}

type NewPersonalMailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewPersonalMailResp) Reset() {
	*x = NewPersonalMailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPersonalMailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPersonalMailResp) ProtoMessage() {}

func (x *NewPersonalMailResp) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPersonalMailResp.ProtoReflect.Descriptor instead.
func (*NewPersonalMailResp) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{11}
}

type VOServerMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId  int32         `protobuf:"varint,2,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Title       string        `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	TitleArgs   []string      `protobuf:"bytes,4,rep,name=titleArgs,proto3" json:"titleArgs,omitempty"`
	Content     string        `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ContentArgs []string      `protobuf:"bytes,6,rep,name=contentArgs,proto3" json:"contentArgs,omitempty"`
	Attachment  []*VOResource `protobuf:"bytes,7,rep,name=attachment,proto3" json:"attachment,omitempty"`
	Sender      string        `protobuf:"bytes,8,opt,name=sender,proto3" json:"sender,omitempty"`
	SendTime    int64         `protobuf:"varint,9,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	ExpireTime  int64         `protobuf:"varint,10,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	EndTime     int64         `protobuf:"varint,11,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *VOServerMail) Reset() {
	*x = VOServerMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VOServerMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VOServerMail) ProtoMessage() {}

func (x *VOServerMail) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VOServerMail.ProtoReflect.Descriptor instead.
func (*VOServerMail) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{12}
}

func (x *VOServerMail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VOServerMail) GetTemplateId() int32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *VOServerMail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VOServerMail) GetTitleArgs() []string {
	if x != nil {
		return x.TitleArgs
	}
	return nil
}

func (x *VOServerMail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VOServerMail) GetContentArgs() []string {
	if x != nil {
		return x.ContentArgs
	}
	return nil
}

func (x *VOServerMail) GetAttachment() []*VOResource {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *VOServerMail) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *VOServerMail) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *VOServerMail) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *VOServerMail) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type VOServerGroupMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail    *VOServerMail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	SendAll bool          `protobuf:"varint,2,opt,name=sendAll,proto3" json:"sendAll,omitempty"`
	Users   []int64       `protobuf:"varint,3,rep,packed,name=users,proto3" json:"users,omitempty"`
}

func (x *VOServerGroupMail) Reset() {
	*x = VOServerGroupMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VOServerGroupMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VOServerGroupMail) ProtoMessage() {}

func (x *VOServerGroupMail) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VOServerGroupMail.ProtoReflect.Descriptor instead.
func (*VOServerGroupMail) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{13}
}

func (x *VOServerGroupMail) GetMail() *VOServerMail {
	if x != nil {
		return x.Mail
	}
	return nil
}

func (x *VOServerGroupMail) GetSendAll() bool {
	if x != nil {
		return x.SendAll
	}
	return false
}

func (x *VOServerGroupMail) GetUsers() []int64 {
	if x != nil {
		return x.Users
	}
	return nil
}

type VOServerPersonalMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail *VOServerMail `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	User int64         `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *VOServerPersonalMail) Reset() {
	*x = VOServerPersonalMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_mail_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VOServerPersonalMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VOServerPersonalMail) ProtoMessage() {}

func (x *VOServerPersonalMail) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_mail_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VOServerPersonalMail.ProtoReflect.Descriptor instead.
func (*VOServerPersonalMail) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_mail_proto_rawDescGZIP(), []int{14}
}

func (x *VOServerPersonalMail) GetMail() *VOServerMail {
	if x != nil {
		return x.Mail
	}
	return nil
}

func (x *VOServerPersonalMail) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

var File_shared_protobuf_proto_mail_proto protoreflect.FileDescriptor

var file_shared_protobuf_proto_mail_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x26, 0x0a, 0x0c, 0x4d, 0x61, 0x69, 0x6c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x4d,
	0x61, 0x69, 0x6c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x56, 0x4f, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x33, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4d,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x56, 0x4f, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x0d, 0x70, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xc5, 0x02, 0x0a, 0x16, 0x53, 0x65, 0x6e,
	0x64, 0x57, 0x68, 0x6f, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x19, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x68, 0x6f, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0xd5, 0x02, 0x0a, 0x10,
	0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x41,
	0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x67, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x2b, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0xd8, 0x02, 0x0a, 0x13, 0x53, 0x65, 0x6e,
	0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x41,
	0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x67, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x2b, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x39, 0x0a, 0x0f, 0x4e,
	0x65, 0x77, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x26,
	0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x56,
	0x4f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x12, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x3f, 0x0a, 0x12, 0x4e, 0x65,
	0x77, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x29, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x56, 0x4f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x15, 0x0a, 0x13, 0x4e,
	0x65, 0x77, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x22, 0xc9, 0x02, 0x0a, 0x0c, 0x56, 0x4f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x66,
	0x0a, 0x11, 0x56, 0x4f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x56, 0x4f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x4d, 0x0a, 0x14, 0x56, 0x4f, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x21,
	0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x56,
	0x4f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x32, 0xf1, 0x01, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x26,
	0x0a, 0x05, 0x46, 0x65, 0x74, 0x63, 0x68, 0x12, 0x0d, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x68,
	0x6f, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x17, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x57, 0x68, 0x6f, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x68, 0x6f,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x36, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61, 0x69,
	0x6c, 0x12, 0x11, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_protobuf_proto_mail_proto_rawDescOnce sync.Once
	file_shared_protobuf_proto_mail_proto_rawDescData = file_shared_protobuf_proto_mail_proto_rawDesc
)

func file_shared_protobuf_proto_mail_proto_rawDescGZIP() []byte {
	file_shared_protobuf_proto_mail_proto_rawDescOnce.Do(func() {
		file_shared_protobuf_proto_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_protobuf_proto_mail_proto_rawDescData)
	})
	return file_shared_protobuf_proto_mail_proto_rawDescData
}

var file_shared_protobuf_proto_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_shared_protobuf_proto_mail_proto_goTypes = []interface{}{
	(*MailFetchReq)(nil),            // 0: MailFetchReq
	(*MailFetchResp)(nil),           // 1: MailFetchResp
	(*SendWholeServerMailReq)(nil),  // 2: SendWholeServerMailReq
	(*SendWholeServerMailResp)(nil), // 3: SendWholeServerMailResp
	(*SendGroupMailReq)(nil),        // 4: SendGroupMailReq
	(*SendGroupMailResp)(nil),       // 5: SendGroupMailResp
	(*SendPersonalMailReq)(nil),     // 6: SendPersonalMailReq
	(*SendPersonalMailResp)(nil),    // 7: SendPersonalMailResp
	(*NewGroupMailReq)(nil),         // 8: NewGroupMailReq
	(*NewGroupMailResp)(nil),        // 9: NewGroupMailResp
	(*NewPersonalMailReq)(nil),      // 10: NewPersonalMailReq
	(*NewPersonalMailResp)(nil),     // 11: NewPersonalMailResp
	(*VOServerMail)(nil),            // 12: VOServerMail
	(*VOServerGroupMail)(nil),       // 13: VOServerGroupMail
	(*VOServerPersonalMail)(nil),    // 14: VOServerPersonalMail
	(*VOResource)(nil),              // 15: VOResource
}
var file_shared_protobuf_proto_mail_proto_depIdxs = []int32{
	12, // 0: MailFetchResp.groupMails:type_name -> VOServerMail
	12, // 1: MailFetchResp.personalMails:type_name -> VOServerMail
	15, // 2: SendWholeServerMailReq.attachment:type_name -> VOResource
	15, // 3: SendGroupMailReq.attachment:type_name -> VOResource
	15, // 4: SendPersonalMailReq.attachment:type_name -> VOResource
	13, // 5: NewGroupMailReq.mail:type_name -> VOServerGroupMail
	14, // 6: NewPersonalMailReq.mail:type_name -> VOServerPersonalMail
	15, // 7: VOServerMail.attachment:type_name -> VOResource
	12, // 8: VOServerGroupMail.mail:type_name -> VOServerMail
	12, // 9: VOServerPersonalMail.mail:type_name -> VOServerMail
	0,  // 10: Mail.Fetch:input_type -> MailFetchReq
	2,  // 11: Mail.SendWholeServerMail:input_type -> SendWholeServerMailReq
	4,  // 12: Mail.SendGroupMail:input_type -> SendGroupMailReq
	6,  // 13: Mail.SendPersonalMail:input_type -> SendPersonalMailReq
	1,  // 14: Mail.Fetch:output_type -> MailFetchResp
	3,  // 15: Mail.SendWholeServerMail:output_type -> SendWholeServerMailResp
	5,  // 16: Mail.SendGroupMail:output_type -> SendGroupMailResp
	7,  // 17: Mail.SendPersonalMail:output_type -> SendPersonalMailResp
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_shared_protobuf_proto_mail_proto_init() }
func file_shared_protobuf_proto_mail_proto_init() {
	if File_shared_protobuf_proto_mail_proto != nil {
		return
	}
	file_shared_protobuf_proto_vo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_shared_protobuf_proto_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailFetchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailFetchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendWholeServerMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendWholeServerMailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGroupMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGroupMailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPersonalMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPersonalMailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGroupMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGroupMailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPersonalMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPersonalMailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VOServerMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VOServerGroupMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_mail_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VOServerPersonalMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_protobuf_proto_mail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_protobuf_proto_mail_proto_goTypes,
		DependencyIndexes: file_shared_protobuf_proto_mail_proto_depIdxs,
		MessageInfos:      file_shared_protobuf_proto_mail_proto_msgTypes,
	}.Build()
	File_shared_protobuf_proto_mail_proto = out.File
	file_shared_protobuf_proto_mail_proto_rawDesc = nil
	file_shared_protobuf_proto_mail_proto_goTypes = nil
	file_shared_protobuf_proto_mail_proto_depIdxs = nil
}
