// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.5
// source: shared/protobuf/proto/user_setting.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 设置看板娘
type C2SUserKanban struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=characterId,proto3" json:"characterId,omitempty"`
}

func (x *C2SUserKanban) Reset() {
	*x = C2SUserKanban{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SUserKanban) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SUserKanban) ProtoMessage() {}

func (x *C2SUserKanban) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SUserKanban.ProtoReflect.Descriptor instead.
func (*C2SUserKanban) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{0}
}

func (x *C2SUserKanban) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type S2CUserKanban struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterId int32 `protobuf:"varint,1,opt,name=characterId,proto3" json:"characterId,omitempty"`
}

func (x *S2CUserKanban) Reset() {
	*x = S2CUserKanban{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CUserKanban) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CUserKanban) ProtoMessage() {}

func (x *S2CUserKanban) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CUserKanban.ProtoReflect.Descriptor instead.
func (*S2CUserKanban) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{1}
}

func (x *S2CUserKanban) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

// 设置头像
type C2SUserAvatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avatar int32 `protobuf:"varint,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *C2SUserAvatar) Reset() {
	*x = C2SUserAvatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SUserAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SUserAvatar) ProtoMessage() {}

func (x *C2SUserAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SUserAvatar.ProtoReflect.Descriptor instead.
func (*C2SUserAvatar) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{2}
}

func (x *C2SUserAvatar) GetAvatar() int32 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

type S2CUserAvatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avatar int32 `protobuf:"varint,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *S2CUserAvatar) Reset() {
	*x = S2CUserAvatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CUserAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CUserAvatar) ProtoMessage() {}

func (x *S2CUserAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CUserAvatar.ProtoReflect.Descriptor instead.
func (*S2CUserAvatar) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{3}
}

func (x *S2CUserAvatar) GetAvatar() int32 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

// 设置昵称
type C2SUserNickname struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *C2SUserNickname) Reset() {
	*x = C2SUserNickname{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SUserNickname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SUserNickname) ProtoMessage() {}

func (x *C2SUserNickname) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SUserNickname.ProtoReflect.Descriptor instead.
func (*C2SUserNickname) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{4}
}

func (x *C2SUserNickname) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type S2CUserNickname struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname       string            `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	NameIndex      int32             `protobuf:"varint,2,opt,name=nameIndex,proto3" json:"nameIndex,omitempty"`
	ResourceResult *VOResourceResult `protobuf:"bytes,3,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"` //资源消耗
}

func (x *S2CUserNickname) Reset() {
	*x = S2CUserNickname{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CUserNickname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CUserNickname) ProtoMessage() {}

func (x *S2CUserNickname) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CUserNickname.ProtoReflect.Descriptor instead.
func (*S2CUserNickname) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{5}
}

func (x *S2CUserNickname) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *S2CUserNickname) GetNameIndex() int32 {
	if x != nil {
		return x.NameIndex
	}
	return 0
}

func (x *S2CUserNickname) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

// 设置签名
type C2SUserSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *C2SUserSignature) Reset() {
	*x = C2SUserSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SUserSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SUserSignature) ProtoMessage() {}

func (x *C2SUserSignature) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SUserSignature.ProtoReflect.Descriptor instead.
func (*C2SUserSignature) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{6}
}

func (x *C2SUserSignature) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type S2CUserSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *S2CUserSignature) Reset() {
	*x = S2CUserSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CUserSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CUserSignature) ProtoMessage() {}

func (x *S2CUserSignature) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CUserSignature.ProtoReflect.Descriptor instead.
func (*S2CUserSignature) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{7}
}

func (x *S2CUserSignature) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// 设置名片展示角色
type C2SVisitingCardSetCharacter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PosList []*VOCharacterPos `protobuf:"bytes,1,rep,name=posList,proto3" json:"posList,omitempty"`
}

func (x *C2SVisitingCardSetCharacter) Reset() {
	*x = C2SVisitingCardSetCharacter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SVisitingCardSetCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SVisitingCardSetCharacter) ProtoMessage() {}

func (x *C2SVisitingCardSetCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SVisitingCardSetCharacter.ProtoReflect.Descriptor instead.
func (*C2SVisitingCardSetCharacter) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{8}
}

func (x *C2SVisitingCardSetCharacter) GetPosList() []*VOCharacterPos {
	if x != nil {
		return x.PosList
	}
	return nil
}

type S2CVisitingCardSetCharacter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CVisitingCardSetCharacter) Reset() {
	*x = S2CVisitingCardSetCharacter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CVisitingCardSetCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CVisitingCardSetCharacter) ProtoMessage() {}

func (x *S2CVisitingCardSetCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CVisitingCardSetCharacter.ProtoReflect.Descriptor instead.
func (*S2CVisitingCardSetCharacter) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{9}
}

// 设置名片展示世界级道具
type C2SVisitingCardSetWorldItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldItemUId int64 `protobuf:"varint,1,opt,name=worldItemUId,proto3" json:"worldItemUId,omitempty"`
}

func (x *C2SVisitingCardSetWorldItem) Reset() {
	*x = C2SVisitingCardSetWorldItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SVisitingCardSetWorldItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SVisitingCardSetWorldItem) ProtoMessage() {}

func (x *C2SVisitingCardSetWorldItem) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SVisitingCardSetWorldItem.ProtoReflect.Descriptor instead.
func (*C2SVisitingCardSetWorldItem) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{10}
}

func (x *C2SVisitingCardSetWorldItem) GetWorldItemUId() int64 {
	if x != nil {
		return x.WorldItemUId
	}
	return 0
}

type S2CVisitingCardSetWorldItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CVisitingCardSetWorldItem) Reset() {
	*x = S2CVisitingCardSetWorldItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CVisitingCardSetWorldItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CVisitingCardSetWorldItem) ProtoMessage() {}

func (x *S2CVisitingCardSetWorldItem) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CVisitingCardSetWorldItem.ProtoReflect.Descriptor instead.
func (*S2CVisitingCardSetWorldItem) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{11}
}

// 查看名片信息
type C2SVisitingCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *C2SVisitingCard) Reset() {
	*x = C2SVisitingCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SVisitingCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SVisitingCard) ProtoMessage() {}

func (x *C2SVisitingCard) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SVisitingCard.ProtoReflect.Descriptor instead.
func (*C2SVisitingCard) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{12}
}

func (x *C2SVisitingCard) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type S2CVisitingCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *VOVisitingCard `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *S2CVisitingCard) Reset() {
	*x = S2CVisitingCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CVisitingCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CVisitingCard) ProtoMessage() {}

func (x *S2CVisitingCard) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CVisitingCard.ProtoReflect.Descriptor instead.
func (*S2CVisitingCard) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{13}
}

func (x *S2CVisitingCard) GetCard() *VOVisitingCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type VOCharacterVisitingCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos       int32            `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Character *VOUserCharacter `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
}

func (x *VOCharacterVisitingCard) Reset() {
	*x = VOCharacterVisitingCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VOCharacterVisitingCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VOCharacterVisitingCard) ProtoMessage() {}

func (x *VOCharacterVisitingCard) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VOCharacterVisitingCard.ProtoReflect.Descriptor instead.
func (*VOCharacterVisitingCard) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{14}
}

func (x *VOCharacterVisitingCard) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *VOCharacterVisitingCard) GetCharacter() *VOUserCharacter {
	if x != nil {
		return x.Character
	}
	return nil
}

type VOVisitingCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo            *VOUserInfo                `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	RegisterAt          int64                      `protobuf:"varint,2,opt,name=registerAt,proto3" json:"registerAt,omitempty"`                   // 注册日期
	Signature           string                     `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                      // 签名
	ExploreLevel        int32                      `protobuf:"varint,4,opt,name=exploreLevel,proto3" json:"exploreLevel,omitempty"`               // 主线进度
	ManualProgress      int32                      `protobuf:"varint,5,opt,name=manualProgress,proto3" json:"manualProgress,omitempty"`           // 图鉴收集进度，包括角色世界级道具和主线(百分比)
	AchievementProgress int32                      `protobuf:"varint,6,opt,name=achievementProgress,proto3" json:"achievementProgress,omitempty"` // 成就完成进度
	Characters          []*VOCharacterVisitingCard `protobuf:"bytes,7,rep,name=characters,proto3" json:"characters,omitempty"`                    // 展示的角色
	WorldItemId         int32                      `protobuf:"varint,8,opt,name=worldItemId,proto3" json:"worldItemId,omitempty"`                 // 展示的世界级道具
	WorldItemUId        int64                      `protobuf:"varint,9,opt,name=worldItemUId,proto3" json:"worldItemUId,omitempty"`               // 展示的世界级道具UId
}

func (x *VOVisitingCard) Reset() {
	*x = VOVisitingCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VOVisitingCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VOVisitingCard) ProtoMessage() {}

func (x *VOVisitingCard) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VOVisitingCard.ProtoReflect.Descriptor instead.
func (*VOVisitingCard) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{15}
}

func (x *VOVisitingCard) GetUserInfo() *VOUserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *VOVisitingCard) GetRegisterAt() int64 {
	if x != nil {
		return x.RegisterAt
	}
	return 0
}

func (x *VOVisitingCard) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VOVisitingCard) GetExploreLevel() int32 {
	if x != nil {
		return x.ExploreLevel
	}
	return 0
}

func (x *VOVisitingCard) GetManualProgress() int32 {
	if x != nil {
		return x.ManualProgress
	}
	return 0
}

func (x *VOVisitingCard) GetAchievementProgress() int32 {
	if x != nil {
		return x.AchievementProgress
	}
	return 0
}

func (x *VOVisitingCard) GetCharacters() []*VOCharacterVisitingCard {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *VOVisitingCard) GetWorldItemId() int32 {
	if x != nil {
		return x.WorldItemId
	}
	return 0
}

func (x *VOVisitingCard) GetWorldItemUId() int64 {
	if x != nil {
		return x.WorldItemUId
	}
	return 0
}

// 整点奖励领取情况
type C2SDailyGiftInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SDailyGiftInfo) Reset() {
	*x = C2SDailyGiftInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SDailyGiftInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SDailyGiftInfo) ProtoMessage() {}

func (x *C2SDailyGiftInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SDailyGiftInfo.ProtoReflect.Descriptor instead.
func (*C2SDailyGiftInfo) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{16}
}

type S2CDailyGiftInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rewarded []bool `protobuf:"varint,1,rep,packed,name=rewarded,proto3" json:"rewarded,omitempty"`
}

func (x *S2CDailyGiftInfo) Reset() {
	*x = S2CDailyGiftInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CDailyGiftInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CDailyGiftInfo) ProtoMessage() {}

func (x *S2CDailyGiftInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CDailyGiftInfo.ProtoReflect.Descriptor instead.
func (*S2CDailyGiftInfo) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{17}
}

func (x *S2CDailyGiftInfo) GetRewarded() []bool {
	if x != nil {
		return x.Rewarded
	}
	return nil
}

// 领取整点奖励
type C2SGetDailyGiftReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 传参从0开始
}

func (x *C2SGetDailyGiftReward) Reset() {
	*x = C2SGetDailyGiftReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SGetDailyGiftReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGetDailyGiftReward) ProtoMessage() {}

func (x *C2SGetDailyGiftReward) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGetDailyGiftReward.ProtoReflect.Descriptor instead.
func (*C2SGetDailyGiftReward) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{18}
}

func (x *C2SGetDailyGiftReward) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type S2CGetDailyGiftReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rewarded       []bool            `protobuf:"varint,1,rep,packed,name=rewarded,proto3" json:"rewarded,omitempty"`
	ResourceResult *VOResourceResult `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"`
}

func (x *S2CGetDailyGiftReward) Reset() {
	*x = S2CGetDailyGiftReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CGetDailyGiftReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGetDailyGiftReward) ProtoMessage() {}

func (x *S2CGetDailyGiftReward) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGetDailyGiftReward.ProtoReflect.Descriptor instead.
func (*S2CGetDailyGiftReward) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{19}
}

func (x *S2CGetDailyGiftReward) GetRewarded() []bool {
	if x != nil {
		return x.Rewarded
	}
	return nil
}

func (x *S2CGetDailyGiftReward) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

//设置头像框
type C2SUserFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame int32 `protobuf:"varint,1,opt,name=frame,proto3" json:"frame,omitempty"`
}

func (x *C2SUserFrame) Reset() {
	*x = C2SUserFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SUserFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SUserFrame) ProtoMessage() {}

func (x *C2SUserFrame) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SUserFrame.ProtoReflect.Descriptor instead.
func (*C2SUserFrame) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{20}
}

func (x *C2SUserFrame) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

type S2CUserFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame int32 `protobuf:"varint,1,opt,name=frame,proto3" json:"frame,omitempty"`
}

func (x *S2CUserFrame) Reset() {
	*x = S2CUserFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CUserFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CUserFrame) ProtoMessage() {}

func (x *S2CUserFrame) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CUserFrame.ProtoReflect.Descriptor instead.
func (*S2CUserFrame) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{21}
}

func (x *S2CUserFrame) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

//查询是否是第一次改名
type C2SFetchIsFirstRename struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SFetchIsFirstRename) Reset() {
	*x = C2SFetchIsFirstRename{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SFetchIsFirstRename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SFetchIsFirstRename) ProtoMessage() {}

func (x *C2SFetchIsFirstRename) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SFetchIsFirstRename.ProtoReflect.Descriptor instead.
func (*C2SFetchIsFirstRename) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{22}
}

type S2CFetchIsFirstRename struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFirstRename bool `protobuf:"varint,1,opt,name=isFirstRename,proto3" json:"isFirstRename,omitempty"`
}

func (x *S2CFetchIsFirstRename) Reset() {
	*x = S2CFetchIsFirstRename{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CFetchIsFirstRename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CFetchIsFirstRename) ProtoMessage() {}

func (x *S2CFetchIsFirstRename) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_user_setting_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CFetchIsFirstRename.ProtoReflect.Descriptor instead.
func (*S2CFetchIsFirstRename) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_user_setting_proto_rawDescGZIP(), []int{23}
}

func (x *S2CFetchIsFirstRename) GetIsFirstRename() bool {
	if x != nil {
		return x.IsFirstRename
	}
	return false
}

var File_shared_protobuf_proto_user_setting_proto protoreflect.FileDescriptor

var file_shared_protobuf_proto_user_setting_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0d, 0x43, 0x32,
	0x53, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x61, 0x6e, 0x62, 0x61, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x31, 0x0a,
	0x0d, 0x53, 0x32, 0x43, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x61, 0x6e, 0x62, 0x61, 0x6e, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x27, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x55, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x27, 0x0a, 0x0d, 0x53, 0x32, 0x43,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x22, 0x2d, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x86, 0x01, 0x0a, 0x0f, 0x53, 0x32, 0x43, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x30, 0x0a, 0x10, 0x43, 0x32,
	0x53, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x30, 0x0a, 0x10,
	0x53, 0x32, 0x43, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x48,
	0x0a, 0x1b, 0x43, 0x32, 0x53, 0x56, 0x69, 0x73, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72,
	0x64, 0x53, 0x65, 0x74, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x29, 0x0a,
	0x07, 0x70, 0x6f, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x56, 0x4f, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x52,
	0x07, 0x70, 0x6f, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x32, 0x43, 0x56,
	0x69, 0x73, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x1b, 0x43, 0x32, 0x53, 0x56, 0x69,
	0x73, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x49, 0x64, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x32,
	0x43, 0x56, 0x69, 0x73, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x29, 0x0a, 0x0f, 0x43, 0x32, 0x53,
	0x56, 0x69, 0x73, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x0f, 0x53, 0x32, 0x43, 0x56, 0x69, 0x73, 0x69, 0x74,
	0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x56, 0x4f, 0x56, 0x69, 0x73, 0x69, 0x74, 0x69,
	0x6e, 0x67, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x5b, 0x0a, 0x17,
	0x56, 0x4f, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x56, 0x69, 0x73, 0x69, 0x74,
	0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x2e, 0x0a, 0x09, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56,
	0x4f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x09,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x22, 0xf5, 0x02, 0x0a, 0x0e, 0x56, 0x4f,
	0x56, 0x69, 0x73, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x64, 0x12, 0x27, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x56, 0x4f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x6c, 0x6f,
	0x72, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61, 0x6e, 0x75, 0x61,
	0x6c, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x30, 0x0a, 0x13, 0x61, 0x63, 0x68, 0x69, 0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x61, 0x63,
	0x68, 0x69, 0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x38, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x56, 0x4f, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x56, 0x69, 0x73, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x49, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x49,
	0x64, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x47, 0x69, 0x66,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2e, 0x0a, 0x10, 0x53, 0x32, 0x43, 0x44, 0x61, 0x69, 0x6c,
	0x79, 0x47, 0x69, 0x66, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x65, 0x64, 0x22, 0x2d, 0x0a, 0x15, 0x43, 0x32, 0x53, 0x47, 0x65, 0x74, 0x44,
	0x61, 0x69, 0x6c, 0x79, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x22, 0x6e, 0x0a, 0x15, 0x53, 0x32, 0x43, 0x47, 0x65, 0x74, 0x44, 0x61,
	0x69, 0x6c, 0x79, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52,
	0x08, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x24, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x55, 0x73, 0x65, 0x72, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x22, 0x24, 0x0a, 0x0c, 0x53, 0x32,
	0x43, 0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x22, 0x17, 0x0a, 0x15, 0x43, 0x32, 0x53, 0x46, 0x65, 0x74, 0x63, 0x68, 0x49, 0x73, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x15, 0x53, 0x32, 0x43,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x49, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x46, 0x69, 0x72,
	0x73, 0x74, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_protobuf_proto_user_setting_proto_rawDescOnce sync.Once
	file_shared_protobuf_proto_user_setting_proto_rawDescData = file_shared_protobuf_proto_user_setting_proto_rawDesc
)

func file_shared_protobuf_proto_user_setting_proto_rawDescGZIP() []byte {
	file_shared_protobuf_proto_user_setting_proto_rawDescOnce.Do(func() {
		file_shared_protobuf_proto_user_setting_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_protobuf_proto_user_setting_proto_rawDescData)
	})
	return file_shared_protobuf_proto_user_setting_proto_rawDescData
}

var file_shared_protobuf_proto_user_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_shared_protobuf_proto_user_setting_proto_goTypes = []interface{}{
	(*C2SUserKanban)(nil),               // 0: C2SUserKanban
	(*S2CUserKanban)(nil),               // 1: S2CUserKanban
	(*C2SUserAvatar)(nil),               // 2: C2SUserAvatar
	(*S2CUserAvatar)(nil),               // 3: S2CUserAvatar
	(*C2SUserNickname)(nil),             // 4: C2SUserNickname
	(*S2CUserNickname)(nil),             // 5: S2CUserNickname
	(*C2SUserSignature)(nil),            // 6: C2SUserSignature
	(*S2CUserSignature)(nil),            // 7: S2CUserSignature
	(*C2SVisitingCardSetCharacter)(nil), // 8: C2SVisitingCardSetCharacter
	(*S2CVisitingCardSetCharacter)(nil), // 9: S2CVisitingCardSetCharacter
	(*C2SVisitingCardSetWorldItem)(nil), // 10: C2SVisitingCardSetWorldItem
	(*S2CVisitingCardSetWorldItem)(nil), // 11: S2CVisitingCardSetWorldItem
	(*C2SVisitingCard)(nil),             // 12: C2SVisitingCard
	(*S2CVisitingCard)(nil),             // 13: S2CVisitingCard
	(*VOCharacterVisitingCard)(nil),     // 14: VOCharacterVisitingCard
	(*VOVisitingCard)(nil),              // 15: VOVisitingCard
	(*C2SDailyGiftInfo)(nil),            // 16: C2SDailyGiftInfo
	(*S2CDailyGiftInfo)(nil),            // 17: S2CDailyGiftInfo
	(*C2SGetDailyGiftReward)(nil),       // 18: C2SGetDailyGiftReward
	(*S2CGetDailyGiftReward)(nil),       // 19: S2CGetDailyGiftReward
	(*C2SUserFrame)(nil),                // 20: C2SUserFrame
	(*S2CUserFrame)(nil),                // 21: S2CUserFrame
	(*C2SFetchIsFirstRename)(nil),       // 22: C2SFetchIsFirstRename
	(*S2CFetchIsFirstRename)(nil),       // 23: S2CFetchIsFirstRename
	(*VOResourceResult)(nil),            // 24: VOResourceResult
	(*VOCharacterPos)(nil),              // 25: VOCharacterPos
	(*VOUserCharacter)(nil),             // 26: VOUserCharacter
	(*VOUserInfo)(nil),                  // 27: VOUserInfo
}
var file_shared_protobuf_proto_user_setting_proto_depIdxs = []int32{
	24, // 0: S2CUserNickname.resourceResult:type_name -> VOResourceResult
	25, // 1: C2SVisitingCardSetCharacter.posList:type_name -> VOCharacterPos
	15, // 2: S2CVisitingCard.card:type_name -> VOVisitingCard
	26, // 3: VOCharacterVisitingCard.character:type_name -> VOUserCharacter
	27, // 4: VOVisitingCard.userInfo:type_name -> VOUserInfo
	14, // 5: VOVisitingCard.characters:type_name -> VOCharacterVisitingCard
	24, // 6: S2CGetDailyGiftReward.resourceResult:type_name -> VOResourceResult
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_shared_protobuf_proto_user_setting_proto_init() }
func file_shared_protobuf_proto_user_setting_proto_init() {
	if File_shared_protobuf_proto_user_setting_proto != nil {
		return
	}
	file_shared_protobuf_proto_vo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_shared_protobuf_proto_user_setting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SUserKanban); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CUserKanban); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SUserAvatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CUserAvatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SUserNickname); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CUserNickname); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SUserSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CUserSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SVisitingCardSetCharacter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CVisitingCardSetCharacter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SVisitingCardSetWorldItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CVisitingCardSetWorldItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SVisitingCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CVisitingCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VOCharacterVisitingCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VOVisitingCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SDailyGiftInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CDailyGiftInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SGetDailyGiftReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CGetDailyGiftReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SUserFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CUserFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SFetchIsFirstRename); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_user_setting_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CFetchIsFirstRename); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_protobuf_proto_user_setting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_protobuf_proto_user_setting_proto_goTypes,
		DependencyIndexes: file_shared_protobuf_proto_user_setting_proto_depIdxs,
		MessageInfos:      file_shared_protobuf_proto_user_setting_proto_msgTypes,
	}.Build()
	File_shared_protobuf_proto_user_setting_proto = out.File
	file_shared_protobuf_proto_user_setting_proto_rawDesc = nil
	file_shared_protobuf_proto_user_setting_proto_goTypes = nil
	file_shared_protobuf_proto_user_setting_proto_depIdxs = nil
}
