// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.5
// source: shared/protobuf/proto/world_item.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------ 强化世界级道具 ------------
type C2SWorldItemStrengthen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                      // 强化世界级道具的唯一ID
	Materials []int64 `protobuf:"varint,2,rep,packed,name=materials,proto3" json:"materials,omitempty"` // 素材世界级道具的唯一ID
	Items     []int32 `protobuf:"varint,3,rep,packed,name=items,proto3" json:"items,omitempty"`         // 经验道具数量 长度4，从低到高
}

func (x *C2SWorldItemStrengthen) Reset() {
	*x = C2SWorldItemStrengthen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SWorldItemStrengthen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SWorldItemStrengthen) ProtoMessage() {}

func (x *C2SWorldItemStrengthen) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SWorldItemStrengthen.ProtoReflect.Descriptor instead.
func (*C2SWorldItemStrengthen) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_world_item_proto_rawDescGZIP(), []int{0}
}

func (x *C2SWorldItemStrengthen) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *C2SWorldItemStrengthen) GetMaterials() []int64 {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *C2SWorldItemStrengthen) GetItems() []int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type S2CWorldItemStrengthen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldItem      *VOUserWorldItem  `protobuf:"bytes,1,opt,name=worldItem,proto3" json:"worldItem,omitempty"`           // 世界级道具数据
	ResourceResult *VOResourceResult `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"` // 玩家资源
	Materials      []int64           `protobuf:"varint,3,rep,packed,name=materials,proto3" json:"materials,omitempty"`   // 素材世界级道具的唯一ID
}

func (x *S2CWorldItemStrengthen) Reset() {
	*x = S2CWorldItemStrengthen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CWorldItemStrengthen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CWorldItemStrengthen) ProtoMessage() {}

func (x *S2CWorldItemStrengthen) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CWorldItemStrengthen.ProtoReflect.Descriptor instead.
func (*S2CWorldItemStrengthen) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_world_item_proto_rawDescGZIP(), []int{1}
}

func (x *S2CWorldItemStrengthen) GetWorldItem() *VOUserWorldItem {
	if x != nil {
		return x.WorldItem
	}
	return nil
}

func (x *S2CWorldItemStrengthen) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

func (x *S2CWorldItemStrengthen) GetMaterials() []int64 {
	if x != nil {
		return x.Materials
	}
	return nil
}

// ------------ 突破世界级道具 ------------
type C2SWorldItemAdvance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                      // 突破世界级道具的唯一ID
	Materials []int64 `protobuf:"varint,2,rep,packed,name=materials,proto3" json:"materials,omitempty"` // 素材世界级道具的唯一ID
	ItemID    int32   `protobuf:"varint,3,opt,name=itemID,proto3" json:"itemID,omitempty"`              // 消耗的道具ID
}

func (x *C2SWorldItemAdvance) Reset() {
	*x = C2SWorldItemAdvance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SWorldItemAdvance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SWorldItemAdvance) ProtoMessage() {}

func (x *C2SWorldItemAdvance) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SWorldItemAdvance.ProtoReflect.Descriptor instead.
func (*C2SWorldItemAdvance) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_world_item_proto_rawDescGZIP(), []int{2}
}

func (x *C2SWorldItemAdvance) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *C2SWorldItemAdvance) GetMaterials() []int64 {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *C2SWorldItemAdvance) GetItemID() int32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

type S2CWorldItemAdvance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldItem      *VOUserWorldItem  `protobuf:"bytes,1,opt,name=worldItem,proto3" json:"worldItem,omitempty"`           // 世界级道具数据
	ResourceResult *VOResourceResult `protobuf:"bytes,2,opt,name=resourceResult,proto3" json:"resourceResult,omitempty"` // 玩家资源
	Materials      []int64           `protobuf:"varint,3,rep,packed,name=materials,proto3" json:"materials,omitempty"`   // 素材世界级道具的唯一ID
}

func (x *S2CWorldItemAdvance) Reset() {
	*x = S2CWorldItemAdvance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CWorldItemAdvance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CWorldItemAdvance) ProtoMessage() {}

func (x *S2CWorldItemAdvance) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CWorldItemAdvance.ProtoReflect.Descriptor instead.
func (*S2CWorldItemAdvance) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_world_item_proto_rawDescGZIP(), []int{3}
}

func (x *S2CWorldItemAdvance) GetWorldItem() *VOUserWorldItem {
	if x != nil {
		return x.WorldItem
	}
	return nil
}

func (x *S2CWorldItemAdvance) GetResourceResult() *VOResourceResult {
	if x != nil {
		return x.ResourceResult
	}
	return nil
}

func (x *S2CWorldItemAdvance) GetMaterials() []int64 {
	if x != nil {
		return x.Materials
	}
	return nil
}

// ------------ 世界级道具加锁和解锁 ------------
type C2SWorldItemLock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`         // 世界级道具唯一ID
	IsLock bool  `protobuf:"varint,2,opt,name=isLock,proto3" json:"isLock,omitempty"` // 是否加锁
}

func (x *C2SWorldItemLock) Reset() {
	*x = C2SWorldItemLock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SWorldItemLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SWorldItemLock) ProtoMessage() {}

func (x *C2SWorldItemLock) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SWorldItemLock.ProtoReflect.Descriptor instead.
func (*C2SWorldItemLock) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_world_item_proto_rawDescGZIP(), []int{4}
}

func (x *C2SWorldItemLock) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *C2SWorldItemLock) GetIsLock() bool {
	if x != nil {
		return x.IsLock
	}
	return false
}

type S2CWorldItemLock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`         // 装备唯一ID
	IsLock bool  `protobuf:"varint,2,opt,name=isLock,proto3" json:"isLock,omitempty"` // 是否加锁
}

func (x *S2CWorldItemLock) Reset() {
	*x = S2CWorldItemLock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CWorldItemLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CWorldItemLock) ProtoMessage() {}

func (x *S2CWorldItemLock) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CWorldItemLock.ProtoReflect.Descriptor instead.
func (*S2CWorldItemLock) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_world_item_proto_rawDescGZIP(), []int{5}
}

func (x *S2CWorldItemLock) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *S2CWorldItemLock) GetIsLock() bool {
	if x != nil {
		return x.IsLock
	}
	return false
}

// ------------ 获取世界级道具列表 ------------
type C2SWorldItemList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SWorldItemList) Reset() {
	*x = C2SWorldItemList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SWorldItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SWorldItemList) ProtoMessage() {}

func (x *C2SWorldItemList) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SWorldItemList.ProtoReflect.Descriptor instead.
func (*C2SWorldItemList) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_world_item_proto_rawDescGZIP(), []int{6}
}

type S2CWorldItemList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldItems []*VOUserWorldItem `protobuf:"bytes,1,rep,name=worldItems,proto3" json:"worldItems,omitempty"`  // 世界级道具列表数据
	RecastID   int64              `protobuf:"varint,2,opt,name=recastID,proto3" json:"recastID,omitempty"`     // 重铸世界级道具唯一ID
	RecastCamp int32              `protobuf:"varint,3,opt,name=recastCamp,proto3" json:"recastCamp,omitempty"` // 重铸世界级道具阵营
}

func (x *S2CWorldItemList) Reset() {
	*x = S2CWorldItemList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CWorldItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CWorldItemList) ProtoMessage() {}

func (x *S2CWorldItemList) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protobuf_proto_world_item_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CWorldItemList.ProtoReflect.Descriptor instead.
func (*S2CWorldItemList) Descriptor() ([]byte, []int) {
	return file_shared_protobuf_proto_world_item_proto_rawDescGZIP(), []int{7}
}

func (x *S2CWorldItemList) GetWorldItems() []*VOUserWorldItem {
	if x != nil {
		return x.WorldItems
	}
	return nil
}

func (x *S2CWorldItemList) GetRecastID() int64 {
	if x != nil {
		return x.RecastID
	}
	return 0
}

func (x *S2CWorldItemList) GetRecastCamp() int32 {
	if x != nil {
		return x.RecastCamp
	}
	return 0
}

var File_shared_protobuf_proto_world_item_proto protoreflect.FileDescriptor

var file_shared_protobuf_proto_world_item_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x76, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x16, 0x43, 0x32, 0x53, 0x57,
	0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xa1, 0x01, 0x0a, 0x16, 0x53, 0x32, 0x43, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x65,
	0x6e, 0x12, 0x2e, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56, 0x4f, 0x55, 0x73, 0x65, 0x72, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x5b, 0x0a, 0x13, 0x43, 0x32,
	0x53, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x22, 0x9e, 0x01, 0x0a, 0x13, 0x53, 0x32, 0x43, 0x57,
	0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x2e, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x56, 0x4f, 0x55, 0x73, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6c, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x39, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x56, 0x4f, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61,
	0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x6d,
	0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x3a, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x57,
	0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x73, 0x4c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73,
	0x4c, 0x6f, 0x63, 0x6b, 0x22, 0x3a, 0x0a, 0x10, 0x53, 0x32, 0x43, 0x57, 0x6f, 0x72, 0x6c, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x4c, 0x6f,
	0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4c, 0x6f, 0x63, 0x6b,
	0x22, 0x12, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x10, 0x53, 0x32, 0x43, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0a, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x56, 0x4f, 0x55, 0x73, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x0a, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x63, 0x61, 0x73, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72,
	0x65, 0x63, 0x61, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x61, 0x73,
	0x74, 0x43, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x63,
	0x61, 0x73, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_protobuf_proto_world_item_proto_rawDescOnce sync.Once
	file_shared_protobuf_proto_world_item_proto_rawDescData = file_shared_protobuf_proto_world_item_proto_rawDesc
)

func file_shared_protobuf_proto_world_item_proto_rawDescGZIP() []byte {
	file_shared_protobuf_proto_world_item_proto_rawDescOnce.Do(func() {
		file_shared_protobuf_proto_world_item_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_protobuf_proto_world_item_proto_rawDescData)
	})
	return file_shared_protobuf_proto_world_item_proto_rawDescData
}

var file_shared_protobuf_proto_world_item_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shared_protobuf_proto_world_item_proto_goTypes = []interface{}{
	(*C2SWorldItemStrengthen)(nil), // 0: C2SWorldItemStrengthen
	(*S2CWorldItemStrengthen)(nil), // 1: S2CWorldItemStrengthen
	(*C2SWorldItemAdvance)(nil),    // 2: C2SWorldItemAdvance
	(*S2CWorldItemAdvance)(nil),    // 3: S2CWorldItemAdvance
	(*C2SWorldItemLock)(nil),       // 4: C2SWorldItemLock
	(*S2CWorldItemLock)(nil),       // 5: S2CWorldItemLock
	(*C2SWorldItemList)(nil),       // 6: C2SWorldItemList
	(*S2CWorldItemList)(nil),       // 7: S2CWorldItemList
	(*VOUserWorldItem)(nil),        // 8: VOUserWorldItem
	(*VOResourceResult)(nil),       // 9: VOResourceResult
}
var file_shared_protobuf_proto_world_item_proto_depIdxs = []int32{
	8, // 0: S2CWorldItemStrengthen.worldItem:type_name -> VOUserWorldItem
	9, // 1: S2CWorldItemStrengthen.resourceResult:type_name -> VOResourceResult
	8, // 2: S2CWorldItemAdvance.worldItem:type_name -> VOUserWorldItem
	9, // 3: S2CWorldItemAdvance.resourceResult:type_name -> VOResourceResult
	8, // 4: S2CWorldItemList.worldItems:type_name -> VOUserWorldItem
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_shared_protobuf_proto_world_item_proto_init() }
func file_shared_protobuf_proto_world_item_proto_init() {
	if File_shared_protobuf_proto_world_item_proto != nil {
		return
	}
	file_shared_protobuf_proto_vo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_shared_protobuf_proto_world_item_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SWorldItemStrengthen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_world_item_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CWorldItemStrengthen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_world_item_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SWorldItemAdvance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_world_item_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CWorldItemAdvance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_world_item_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SWorldItemLock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_world_item_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CWorldItemLock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_world_item_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SWorldItemList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_protobuf_proto_world_item_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CWorldItemList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_protobuf_proto_world_item_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_protobuf_proto_world_item_proto_goTypes,
		DependencyIndexes: file_shared_protobuf_proto_world_item_proto_depIdxs,
		MessageInfos:      file_shared_protobuf_proto_world_item_proto_msgTypes,
	}.Build()
	File_shared_protobuf_proto_world_item_proto = out.File
	file_shared_protobuf_proto_world_item_proto_rawDesc = nil
	file_shared_protobuf_proto_world_item_proto_goTypes = nil
	file_shared_protobuf_proto_world_item_proto_depIdxs = nil
}
