# 服务名，表示服务器职能，用于服务发现和负载均衡
Service = "mail"
# 服务器名称，唯一不可重复
ServerName = "mail01"
# grpc地址
GRPCListenPort = "9101"
# csv文件路径
CSVPath = "../shared/csv/data"
# etcd终端
ETCDEndpoints = [
    "127.0.0.1:2379",
	"127.0.0.1:2479",
	"127.0.0.1:2579",
]
# mysql配置
[MySQL]
    Addr = "root:xuecm01,@tcp(localhost:3306)/overlord?charset=utf8mb4&parseTime=true&loc=Local"
    MaxIdleConn = 5
    MaxOpenConn = 5
# redis配置
[Redis]
    Addr = ":6379"
    UserName = "root"
    Password = ""

# log
[Log]
    LogLevel = "DEBUG"
    LogDir = "./log"
    FileSizeLimit = 4294967296